import { ID_PATTERN, SCHEMA_VERSION, candidateFields, enums } from "./domain.mjs";
import { ConversationValidationError, validateAllowedCommentaryVariantProjections, validateInterpreterModelOutput } from "./validators.mjs";

const own = (value, key) => Object.prototype.hasOwnProperty.call(value, key);
function fail(path, code, message) { throw new ConversationValidationError(path, code, message); }
function object(value, path) { if (!value || typeof value !== "object" || Array.isArray(value)) fail(path, "invalid_type", "must be an object"); }
function exact(value, required, path) { object(value, path); const allowed = new Set(required); for (const key of required) if (!own(value, key)) fail(`${path}.${key}`, "missing_field", "is required"); for (const key of Object.keys(value)) if (!allowed.has(key)) fail(`${path}.${key}`, "unknown_field", "is not allowed"); }
function literal(value, expected, path) { if (value !== expected) fail(path, "invalid_literal", `must equal ${expected}`); }
function id(value, path, nullable = false) { if (nullable && value === null) return; if (typeof value !== "string" || !ID_PATTERN.test(value)) fail(path, "invalid_id", "must be an ID"); }
function integer(value, min, max, path) { if (!Number.isInteger(value) || value < min || value > max) fail(path, "invalid_integer", `must be an integer from ${min} to ${max}`); }
function string(value, min, max, path) { if (typeof value !== "string" || [...value].length < min || [...value].length > max) fail(path, "invalid_string", `must contain ${min}-${max} Unicode code points`); }
function oneOf(value, values, path) { if (!values.includes(value)) fail(path, "invalid_enum", "has an unsupported value"); }
function schema(value, path) { literal(value.schemaVersion, SCHEMA_VERSION, `${path}.schemaVersion`); }
function array(value, min, max, path) { if (!Array.isArray(value) || value.length < min || value.length > max) fail(path, "invalid_array", `must contain ${min}-${max} items`); }
function unique(values, key, path) { const seen = new Set(); for (const [index, value] of values.entries()) { const identity = key(value); if (seen.has(identity)) fail(`${path}[${index}]`, "duplicate_id", `duplicate identity ${identity}`); seen.add(identity); } }
function ids(values, min, max, path) { array(values, min, max, path); values.forEach((value, index) => id(value, `${path}[${index}]`)); unique(values, (value) => value, path); }
function bool(value, path) { if (typeof value !== "boolean") fail(path, "invalid_type", "must be boolean"); }
function utc(value, path) { if (typeof value !== "string" || value.length < 20 || value.length > 35 || !/^\d{4}-\d{2}-\d{2}T.*Z$/.test(value) || Number.isNaN(Date.parse(value))) fail(path, "invalid_timestamp", "must be RFC3339 UTC"); }

const projectionFields = Object.freeze({
  public_statement_event: ["eventId", "actorId", "turnId", "occurredPhase"],
  public_question_event: ["eventId", "actorId", "targetId", "turnId", "occurredPhase", "topic"],
  suspicion_event: ["eventId", "actorId", "targetId", "turnId", "occurredPhase"],
  vote_event: ["eventId", "actorId", "targetId", "turnId", "occurredPhase"],
  role_claim_event: ["eventId", "actorId", "claimId", "turnId", "occurredPhase"],
  result_claim_event: ["eventId", "actorId", "claimId", "turnId", "occurredPhase"]
});

export function validatePublicEventProjection(value, path = "publicEventProjection") {
  const fields = projectionFields[value?.projectionType]; if (!fields) fail(`${path}.projectionType`, "invalid_discriminator", "unknown public event projection type");
  exact(value, ["schemaVersion", "projectionType", ...fields], path); schema(value, path);
  fields.filter((key) => !["occurredPhase", "topic"].includes(key)).forEach((key) => id(value[key], `${path}.${key}`));
  oneOf(value.occurredPhase, enums.gamePhase, `${path}.occurredPhase`); if (own(value, "topic")) oneOf(value.topic, enums.questionTopic, `${path}.topic`); return value;
}

export function validateClaimProjection(value, path = "claimProjection") {
  const fields = value?.projectionType === "role_claim" ? ["claimId", "actorId", "claimedRole"] : value?.projectionType === "result_claim" ? ["claimId", "actorId", "targetId", "result"] : fail(`${path}.projectionType`, "invalid_discriminator", "unknown claim projection type");
  exact(value, ["schemaVersion", "projectionType", ...fields], path); schema(value, path); ["claimId", "actorId", "targetId"].filter((key) => own(value, key)).forEach((key) => id(value[key], `${path}.${key}`));
  if (own(value, "claimedRole")) oneOf(value.claimedRole, enums.claimableRole, `${path}.claimedRole`); if (own(value, "result")) oneOf(value.result, enums.claimResult, `${path}.result`); return value;
}

const auxiliaryProjectionFields = Object.freeze({ public_vote: ["voteEventId", "actorId", "targetId", "turnId", "occurredPhase"], execution: ["executionEventId", "executedPlayerId", "turnId", "occurredPhase"], attack_death: ["attackEventId", "attackedPlayerId", "turnId", "occurredPhase"] });
export function validateAuxiliaryProjection(value, path = "projection") { const fields = auxiliaryProjectionFields[value?.projectionType]; if (!fields) fail(`${path}.projectionType`, "invalid_discriminator", "unknown auxiliary projection type"); exact(value, ["schemaVersion", "projectionType", ...fields], path); schema(value, path); fields.filter((key) => key !== "occurredPhase").forEach((key) => id(value[key], `${path}.${key}`)); oneOf(value.occurredPhase, enums.gamePhase, `${path}.occurredPhase`); return value; }

export function validatePublicRosterEntry(value, path = "publicRosterEntry") { exact(value, ["playerId", "displayName", "publicStatus"], path); id(value.playerId, `${path}.playerId`); string(value.displayName, 1, 80, `${path}.displayName`); oneOf(value.publicStatus, ["alive", "dead"], `${path}.publicStatus`); return value; }

function validateProjectionGraph({ publicEvents, publicClaims, publicVotes = [], executions = [], attackDeaths = [], publicRoster }, path) {
  array(publicEvents, 0, 64, `${path}.publicEvents`); publicEvents.forEach((value, index) => validatePublicEventProjection(value, `${path}.publicEvents[${index}]`)); unique(publicEvents, (value) => value.eventId, `${path}.publicEvents`);
  array(publicClaims, 0, 64, `${path}.publicClaims`); publicClaims.forEach((value, index) => validateClaimProjection(value, `${path}.publicClaims[${index}]`)); unique(publicClaims, (value) => value.claimId, `${path}.publicClaims`);
  const auxiliary = [[publicVotes, 32, "publicVotes"], [executions, 16, "executions"], [attackDeaths, 16, "attackDeaths"]]; for (const [values, max, name] of auxiliary) { array(values, 0, max, `${path}.${name}`); values.forEach((value, index) => validateAuxiliaryProjection(value, `${path}.${name}[${index}]`)); unique(values, (value) => value.voteEventId ?? value.executionEventId ?? value.attackEventId, `${path}.${name}`); }
  const allPrimaryIds = [...publicEvents.map((value) => value.eventId), ...publicClaims.map((value) => value.claimId), ...publicVotes.map((value) => value.voteEventId), ...executions.map((value) => value.executionEventId), ...attackDeaths.map((value) => value.attackEventId)]; unique(allPrimaryIds, (value) => value, `${path}.projectionIds`);
  const claims = new Map(publicClaims.map((value) => [value.claimId, value])); for (const event of publicEvents.filter((value) => value.claimId)) { const claim = claims.get(event.claimId), expected = event.projectionType === "role_claim_event" ? "role_claim" : "result_claim"; if (!claim || claim.projectionType !== expected || claim.actorId !== event.actorId) fail(`${path}.publicEvents`, "invalid_reference", "claim event must reference a matching same-request claim"); }
  const voteEvents = new Set(publicEvents.filter((value) => value.projectionType === "vote_event").map((value) => value.eventId)); for (const vote of publicVotes) if (!voteEvents.has(vote.voteEventId)) fail(`${path}.publicVotes`, "invalid_reference", "public vote must reference a same-request vote event");
  if (publicRoster) { const roster = new Set(publicRoster.map((value) => value.playerId)); const participantIds = [...publicEvents.flatMap((value) => [value.actorId, value.targetId].filter(Boolean)), ...publicClaims.flatMap((value) => [value.actorId, value.targetId].filter(Boolean))]; for (const participantId of participantIds) if (!roster.has(participantId)) fail(path, "invalid_reference", `unknown public participant ${participantId}`); }
  return new Set(allPrimaryIds);
}

export function validateRendererRequest(value) {
  const path = "rendererRequest", fields = ["schemaVersion", "requestId", "correlationId", "reactionPlanId", "turnId", "resultingStateVersion", "npcId", "locale", "renderMode", "commentaryPlan", "publicEvents", "publicClaims", "publicVotes", "executions", "attackDeaths", "allowedPublicReferenceIds", "allowedVariants"];
  exact(value, fields, path); schema(value, path); ["requestId", "correlationId", "reactionPlanId", "turnId", "npcId"].forEach((key) => id(value[key], `${path}.${key}`)); integer(value.resultingStateVersion, 1, Infinity, `${path}.resultingStateVersion`); oneOf(value.locale, enums.supportedLocale, `${path}.locale`); literal(value.renderMode, "controlled_commentary", `${path}.renderMode`);
  exact(value.commentaryPlan, ["intent", "allowedPublicReferenceIds"], `${path}.commentaryPlan`); oneOf(value.commentaryPlan.intent, enums.commentaryIntent, `${path}.commentaryPlan.intent`); ids(value.commentaryPlan.allowedPublicReferenceIds, 0, 32, `${path}.commentaryPlan.allowedPublicReferenceIds`); ids(value.allowedPublicReferenceIds, 0, 32, `${path}.allowedPublicReferenceIds`); if (JSON.stringify(value.allowedPublicReferenceIds) !== JSON.stringify(value.commentaryPlan.allowedPublicReferenceIds)) fail(`${path}.allowedPublicReferenceIds`, "reference_mismatch", "must exactly copy commentaryPlan references");
  const projectionIds = validateProjectionGraph(value, path); for (const referenceId of value.allowedPublicReferenceIds) if (!projectionIds.has(referenceId)) fail(`${path}.allowedPublicReferenceIds`, "invalid_reference", `unknown public reference ${referenceId}`);
  validateAllowedCommentaryVariantProjections(value.allowedVariants); if (value.allowedVariants.length < 1 || value.allowedVariants.length > 8) fail(`${path}.allowedVariants`, "invalid_array", "must contain 1-8 variants"); unique(value.allowedVariants, (entry) => entry.variantId, `${path}.allowedVariants`); for (const entry of value.allowedVariants) if (entry.locale !== value.locale || entry.intent !== value.commentaryPlan.intent) fail(`${path}.allowedVariants`, "variant_mismatch", "variant locale and intent must match request"); return value;
}

export function validateRendererModelOutput(value, request) { const path = "rendererModelOutput"; exact(value, ["schemaVersion", "selectedVariantId", "selectedVariantVersion"], path); schema(value, path); id(value.selectedVariantId, `${path}.selectedVariantId`); integer(value.selectedVariantVersion, 1, Infinity, `${path}.selectedVariantVersion`); if (request && !request.allowedVariants.some((entry) => entry.variantId === value.selectedVariantId && entry.variantVersion === value.selectedVariantVersion)) fail(path, "invalid_reference", "selected variant is not allowed by the request"); return value; }

export function validateInterpreterRequest(value) {
  const path = "interpreterRequest", fields = ["schemaVersion", "requestId", "correlationId", "turnId", "preconditionStateVersion", "preconditionPhase", "locale", "rawText", "playerContext", "publicRoster", "allowedCandidateTypes", "publicContext", "limits"];
  exact(value, fields, path); schema(value, path); ["requestId", "correlationId", "turnId"].forEach((key) => id(value[key], `${path}.${key}`)); integer(value.preconditionStateVersion, 0, Infinity, `${path}.preconditionStateVersion`); oneOf(value.preconditionPhase, enums.gamePhase, `${path}.preconditionPhase`); oneOf(value.locale, enums.supportedLocale, `${path}.locale`); string(value.rawText, 1, 2000, `${path}.rawText`);
  exact(value.playerContext, ["playerId", "publicStatus"], `${path}.playerContext`); id(value.playerContext.playerId, `${path}.playerContext.playerId`); oneOf(value.playerContext.publicStatus, ["alive", "dead"], `${path}.playerContext.publicStatus`);
  array(value.publicRoster, 1, 16, `${path}.publicRoster`); value.publicRoster.forEach((entry, index) => validatePublicRosterEntry(entry, `${path}.publicRoster[${index}]`)); unique(value.publicRoster, (entry) => entry.playerId, `${path}.publicRoster`); if (!value.publicRoster.some((entry) => entry.playerId === value.playerContext.playerId && entry.publicStatus === value.playerContext.publicStatus)) fail(`${path}.playerContext`, "invalid_reference", "player context must match the public roster");
  ids(value.allowedCandidateTypes, 1, 8, `${path}.allowedCandidateTypes`); value.allowedCandidateTypes.forEach((type, index) => oneOf(type, Object.keys(candidateFields), `${path}.allowedCandidateTypes[${index}]`));
  exact(value.publicContext, ["publicEvents", "publicClaims"], `${path}.publicContext`); validateProjectionGraph({ ...value.publicContext, publicRoster: value.publicRoster }, `${path}.publicContext`);
  exact(value.limits, ["maxAlternatives", "maxActsPerAlternative", "maxNestingDepth"], `${path}.limits`); integer(value.limits.maxAlternatives, 1, 3, `${path}.limits.maxAlternatives`); integer(value.limits.maxActsPerAlternative, 1, 4, `${path}.limits.maxActsPerAlternative`); integer(value.limits.maxNestingDepth, 1, 8, `${path}.limits.maxNestingDepth`); return value;
}

export function validateProviderDiagnostics(value, path = "providerDiagnostics") { exact(value, ["providerName", "model", "attemptCount", "elapsedMs"], path); string(value.providerName, 1, 64, `${path}.providerName`); string(value.model, 1, 128, `${path}.model`); integer(value.attemptCount, 1, 3, `${path}.attemptCount`); integer(value.elapsedMs, 0, Infinity, `${path}.elapsedMs`); return value; }
export function validateInterpreterProviderResult(value, request) { const path = "interpreterProviderResult"; exact(value, ["schemaVersion", "requestId", "correlationId", "modelOutput", "diagnostics"], path); schema(value, path); id(value.requestId, `${path}.requestId`); id(value.correlationId, `${path}.correlationId`); validateInterpreterModelOutput(value.modelOutput, request?.rawText ?? "x"); validateProviderDiagnostics(value.diagnostics, `${path}.diagnostics`); if (request && (value.requestId !== request.requestId || value.correlationId !== request.correlationId)) fail(path, "correlation_mismatch", "provider result must match request identity"); return value; }
export function validateRendererProviderResult(value, request) { const path = "rendererProviderResult"; exact(value, ["schemaVersion", "requestId", "correlationId", "reactionPlanId", "modelOutput", "diagnostics"], path); schema(value, path); ["requestId", "correlationId", "reactionPlanId"].forEach((key) => id(value[key], `${path}.${key}`)); validateRendererModelOutput(value.modelOutput, request); validateProviderDiagnostics(value.diagnostics, `${path}.diagnostics`); if (request && ["requestId", "correlationId", "reactionPlanId"].some((key) => value[key] !== request[key])) fail(path, "correlation_mismatch", "provider result must match renderer request identity"); return value; }

export function validateInterpreterHttpResponse(value, request) { const path = "interpreterHttpResponse"; exact(value, ["schemaVersion", "requestId", "correlationId", "serverCorrelationId", "result"], path); schema(value, path); ["requestId", "correlationId", "serverCorrelationId"].forEach((key) => id(value[key], `${path}.${key}`)); validateInterpreterProviderResult(value.result, request); if (request && (value.requestId !== request.requestId || value.correlationId !== request.correlationId || value.result.requestId !== value.requestId || value.result.correlationId !== value.correlationId)) fail(path, "correlation_mismatch", "HTTP response identity must match request and nested result"); return value; }
export function validateRendererHttpResponse(value, request) { const path = "rendererHttpResponse"; exact(value, ["schemaVersion", "requestId", "correlationId", "serverCorrelationId", "reactionPlanId", "result"], path); schema(value, path); ["requestId", "correlationId", "serverCorrelationId", "reactionPlanId"].forEach((key) => id(value[key], `${path}.${key}`)); validateRendererProviderResult(value.result, request); if (request && ["requestId", "correlationId", "reactionPlanId"].some((key) => value[key] !== request[key] || value.result[key] !== value[key])) fail(path, "correlation_mismatch", "HTTP response identity must match request and nested result"); return value; }

export function validateRendererCorrelationChain({ reactionPlan, rendererRequest, pendingRendererRequest, providerResult, httpResponse }) { validateRendererRequest(rendererRequest); validatePendingConversationRequest(pendingRendererRequest); validateRendererProviderResult(providerResult, rendererRequest); validateRendererHttpResponse(httpResponse, rendererRequest); const correlationId = rendererRequest.correlationId; if (pendingRendererRequest.pendingType !== "renderer" || reactionPlan?.correlationId !== correlationId || pendingRendererRequest.correlationId !== correlationId || providerResult.correlationId !== correlationId || httpResponse.correlationId !== correlationId) fail("rendererCorrelation", "correlation_mismatch", "renderer correlation chain must match exactly"); if (reactionPlan.reactionPlanId !== rendererRequest.reactionPlanId || pendingRendererRequest.reactionPlanId !== rendererRequest.reactionPlanId || pendingRendererRequest.requestId !== rendererRequest.requestId || pendingRendererRequest.turnId !== rendererRequest.turnId || pendingRendererRequest.resultingStateVersion !== rendererRequest.resultingStateVersion || pendingRendererRequest.targetNpcId !== rendererRequest.npcId || pendingRendererRequest.locale !== rendererRequest.locale) fail("rendererCorrelation", "renderer_context_mismatch", "renderer chain must use one request, reaction, turn, version, actor, and locale"); return true; }

export function validatePendingConversationRequest(value) { const path = "pendingConversationRequest"; if (value?.pendingType === "interpreter") { exact(value, ["schemaVersion", "pendingType", "requestId", "correlationId", "turnId", "preconditionStateVersion", "inputRecordId", "targetNpcId", "operation", "status", "startedAt"], path); schema(value, path); ["requestId", "correlationId", "turnId", "inputRecordId", "targetNpcId"].forEach((key) => id(value[key], `${path}.${key}`)); integer(value.preconditionStateVersion, 0, Infinity, `${path}.preconditionStateVersion`); literal(value.operation, "interpret_player_input", `${path}.operation`); } else if (value?.pendingType === "renderer") { exact(value, ["schemaVersion", "pendingType", "requestId", "correlationId", "causationId", "turnId", "resultingStateVersion", "reactionPlanId", "originatingInputRecordId", "locale", "targetNpcId", "operation", "status", "startedAt"], path); schema(value, path); ["requestId", "correlationId", "causationId", "turnId", "reactionPlanId", "originatingInputRecordId", "targetNpcId"].forEach((key) => id(value[key], `${path}.${key}`)); integer(value.resultingStateVersion, 1, Infinity, `${path}.resultingStateVersion`); oneOf(value.locale, enums.supportedLocale, `${path}.locale`); literal(value.operation, "render_npc_utterance", `${path}.operation`); } else fail(`${path}.pendingType`, "invalid_discriminator", "unknown pending request type"); oneOf(value.status, ["pending", "aborting", "completed", "failed"], `${path}.status`); utc(value.startedAt, `${path}.startedAt`); return value; }

export function validateClarificationOutcome(value, publicRoster = []) { const path = "clarificationOutcome"; exact(value, ["schemaVersion", "requestId", "correlationId", "turnId", "preconditionStateVersion", "reason", "templateId", "allowedTargetIds"], path); schema(value, path); ["requestId", "correlationId", "turnId"].forEach((key) => id(value[key], `${path}.${key}`)); integer(value.preconditionStateVersion, 0, Infinity, `${path}.preconditionStateVersion`); oneOf(value.reason, ["ambiguous_target", "ambiguous_intent", "multiple_alternatives", "uninterpretable"], `${path}.reason`); oneOf(value.templateId, ["ask_for_target", "ask_for_clarification", "report_gibberish"], `${path}.templateId`); ids(value.allowedTargetIds, 0, 16, `${path}.allowedTargetIds`); const rosterIds = new Set(publicRoster.map((entry) => entry.playerId)); for (const targetId of value.allowedTargetIds) if (!rosterIds.has(targetId)) fail(`${path}.allowedTargetIds`, "invalid_reference", `unknown target ${targetId}`); return value; }

const errorCodes = ["malformed_json", "invalid_schema", "unsupported_schema_version", "idempotency_conflict", "body_too_large", "unsupported_media_type", "server_rate_limited", "invalid_provider_response", "provider_auth_failure", "provider_unavailable", "provider_timeout"];
export function validateErrorEnvelope(value) { const path = "errorEnvelope"; exact(value, ["schemaVersion", "requestId", "correlationId", "error"], path); schema(value, path); id(value.requestId, `${path}.requestId`, true); id(value.correlationId, `${path}.correlationId`); exact(value.error, ["code", "retryable"], `${path}.error`); oneOf(value.error.code, errorCodes, `${path}.error.code`); bool(value.error.retryable, `${path}.error.retryable`); const neverRetryable = new Set(["malformed_json", "invalid_schema", "unsupported_schema_version", "idempotency_conflict", "body_too_large", "unsupported_media_type", "invalid_provider_response", "provider_auth_failure"]); if (neverRetryable.has(value.error.code) && value.error.retryable) fail(`${path}.error.retryable`, "retry_policy_mismatch", "error code is never client-retryable"); return value; }
