import { canonicalJson } from "./ids.mjs";
import { resolveHistoricalVariant, validateRendererSelection } from "./canonicalRenderer.mjs";
import { ConversationValidationError, validatePendingRendererRequest } from "./validators.mjs";

function fail(path, code, message) { throw new ConversationValidationError(path, code, message); }
function uniqueIndex(values, key, label) { const index = new Map(); values.forEach((value, position) => { const id = value[key]; if (index.has(id)) fail(`${label}[${position}].${key}`, "duplicate_id", `duplicate ${key} ${id}`); index.set(id, value); }); return index; }
function sameSource(left, right) {
  if (left?.sourceType !== right?.sourceType) return false;
  if (left.sourceType === "player_accepted_act") return right.acceptedSpeechActIds?.includes(left.acceptedSpeechActId);
  return left.reactionPlanId === right.reactionPlanId && left.descriptorId === right.descriptorId;
}
function claimPayload(claim) { return claim.type === "role_claim" ? { claimedRole: claim.claimedRole } : { targetId: claim.targetId, result: claim.result }; }
function sameSubject(left, right) { return left.actorId === right.actorId && left.type === right.type && (left.type === "role_claim" || left.targetId === right.targetId); }

const pendingStatusForReason = Object.freeze({ renderer_selected: "pending", renderer_timeout_fallback: "pending", renderer_error_fallback: "pending", renderer_invalid_output_fallback: "pending", renderer_abort_fallback: "aborting" });
const fallbackReasons = new Set(["renderer_timeout_fallback", "renderer_abort_fallback", "renderer_error_fallback", "renderer_invalid_output_fallback"]);
const finalizationIdentityFields = Object.freeze(["publicationId", "reservationId", "reactionPlanId", "source", "locale", "selectedVariantId", "selectedVariantVersion", "fallbackUsed", "finalizationReason", "publicationSlotOrder"]);

export function classifyPublicationFinalizationAttempt({ candidate, existingFinalizations = [] }) {
  const existing = existingFinalizations.find((record) => record.publicationId === candidate.publicationId);
  if (!existing) return { classification: "new", existingFinalization: null, code: null };
  const identical = finalizationIdentityFields.every((key) => canonicalJson(existing[key]) === canonicalJson(candidate[key]));
  return identical ? { classification: "replay", existingFinalization: existing, code: "finalization_replay" } : { classification: "conflict", existingFinalization: existing, code: "idempotency_conflict" };
}

export function validateClaimReferences(claims, { acceptedSpeechActs = [], reactionPlans = [] } = {}) {
  const acts = uniqueIndex(acceptedSpeechActs, "speechActId", "acceptedSpeechActs"), plans = uniqueIndex(reactionPlans, "reactionPlanId", "reactionPlans"), claimIndex = uniqueIndex(claims, "claimId", "claims");
  claims.forEach((claim, position) => {
    if (claim.source.sourceType === "player_accepted_act") for (const actId of claim.source.acceptedSpeechActIds) { const act = acts.get(actId); if (!act || act.inputRecordId !== claim.source.inputRecordId || act.requestId !== claim.source.requestId || act.actorId !== claim.actorId) fail(`claims[${position}].source`, "invalid_reference", `invalid player claim source ${actId}`); const typeMatches = claim.type === "role_claim" ? act.type === "accepted_role_claim" : act.type === "accepted_result_claim", payloadMatches = claim.type === "role_claim" ? act.claimedRole === claim.claimedRole : act.targetId === claim.targetId && act.result === claim.result; if (!typeMatches) fail(`claims[${position}].source`, "claim_source_type_mismatch", "accepted speech act type does not match claim type"); if (!payloadMatches) fail(`claims[${position}].source`, "claim_source_payload_mismatch", "every accepted speech act must carry the canonical claim payload"); }
    else { const plan = plans.get(claim.source.reactionPlanId), descriptor = plan?.intendedSpeechActs.find((item) => item.descriptorId === claim.source.descriptorId); if (!plan || plan.npcId !== claim.actorId || plan.originatingInputRecordId !== claim.source.originatingInputRecordId || plan.requestId !== claim.source.reactionCommitRequestId || descriptor?.descriptorType !== claim.type) fail(`claims[${position}].source`, "claim_source_type_mismatch", "invalid NPC claim source or descriptor type"); const payloadMatches = claim.type === "role_claim" ? descriptor.claimedRole === claim.claimedRole : descriptor.targetId === claim.targetId && descriptor.result === claim.result; if (!payloadMatches) fail(`claims[${position}].source`, "claim_source_payload_mismatch", "reaction descriptor payload does not match claim payload"); }
    const repeat = claim.repeatsClaimId ? claimIndex.get(claim.repeatsClaimId) : null;
    if (repeat) { if (repeat.claimId === claim.claimId || repeat.createdStateVersion >= claim.createdStateVersion) fail(`claims[${position}].repeatsClaimId`, "future_reference", "repeat must reference a claim from a lower state version"); if (!sameSubject(claim, repeat) || canonicalJson(claimPayload(claim)) !== canonicalJson(claimPayload(repeat))) fail(`claims[${position}].repeatsClaimId`, "invalid_repeat", "repeat actor, type, subject, and payload must match"); }
    else if (claim.repeatsClaimId) fail(`claims[${position}].repeatsClaimId`, "dangling_reference", "repeat claim does not exist");
    for (const relatedId of claim.contradictsClaimIds) { const prior = claimIndex.get(relatedId); if (!prior) fail(`claims[${position}].contradictsClaimIds`, "dangling_reference", `claim ${relatedId} does not exist`); if (prior.claimId === claim.claimId || prior.createdStateVersion >= claim.createdStateVersion) fail(`claims[${position}].contradictsClaimIds`, "future_reference", "contradiction must reference a claim from a lower state version"); if (!sameSubject(claim, prior) || canonicalJson(claimPayload(claim)) === canonicalJson(claimPayload(prior))) fail(`claims[${position}].contradictsClaimIds`, "invalid_contradiction", "contradiction must have the same actor/type/subject and conflicting payload"); }
  }); return true;
}

const playerEventCompatibility = Object.freeze({ public_statement_recorded: "accepted_non_game_statement", public_question_recorded: "accepted_question", suspicion_expressed: "accepted_suspicion", vote_declared: "accepted_vote_declaration", role_claim_recorded: "accepted_role_claim", result_claim_recorded: "accepted_result_claim" });
const npcEventCompatibility = Object.freeze({ suspicion_expressed: "suspicion", vote_declared: "vote_declaration", role_claim_recorded: "role_claim", result_claim_recorded: "result_claim" });
export function validateEventReferences(events, { acceptedSpeechActs = [], reactionPlans = [], claims = [] } = {}) {
  const acts = uniqueIndex(acceptedSpeechActs, "speechActId", "acceptedSpeechActs"), plans = uniqueIndex(reactionPlans, "reactionPlanId", "reactionPlans"), claimIndex = uniqueIndex(claims, "claimId", "claims");
  events.forEach((event, position) => {
    if (event.source.sourceType === "player_accepted_act") { const act = acts.get(event.source.acceptedSpeechActId); if (!act || act.inputRecordId !== event.source.inputRecordId || act.requestId !== event.source.requestId || act.actorId !== event.actorId || act.acceptedPhase !== event.occurredPhase || act.type !== playerEventCompatibility[event.eventType]) fail(`events[${position}].source`, "incompatible_source", "accepted speech act is incompatible with event type, actor, request, input, or phase"); }
    else { const plan = plans.get(event.source.reactionPlanId), descriptor = plan?.intendedSpeechActs.find((item) => item.descriptorId === event.source.descriptorId); if (!plan || plan.npcId !== event.actorId || plan.originatingInputRecordId !== event.source.originatingInputRecordId || plan.requestId !== event.source.reactionCommitRequestId || descriptor?.descriptorType !== npcEventCompatibility[event.eventType]) fail(`events[${position}].source`, "incompatible_source", "reaction descriptor is incompatible with event type"); }
    if (event.claimId) { const claim = claimIndex.get(event.claimId), expected = event.eventType === "role_claim_recorded" ? "role_claim" : "result_claim"; if (!claim || claim.type !== expected || claim.actorId !== event.actorId || !sameSource(event.source, claim.source)) fail(`events[${position}].claimId`, "incompatible_claim", "claim event and canonical claim provenance must agree"); const sourceRequest = claim.source.requestId ?? claim.source.reactionCommitRequestId; if (event.requestId !== sourceRequest) fail(`events[${position}].requestId`, "request_mismatch", "event and claim request must match"); }
  }); return true;
}

export function validateReactionPlanReferences(reactionPlans, { inputRecords = [], events = [] } = {}) { const inputs = uniqueIndex(inputRecords, "inputRecordId", "inputRecords"), eventIndex = uniqueIndex(events, "eventId", "events"); reactionPlans.forEach((plan, position) => { const input = inputs.get(plan.originatingInputRecordId); if (!input || input.locale !== plan.locale || input.turnId !== plan.turnId) fail(`reactionPlans[${position}].originatingInputRecordId`, "invalid_reference", "originating input, locale, and turn must match"); for (const eventId of plan.causationEventIds) { const event = eventIndex.get(eventId); if (!event || event.stateVersion >= plan.resultingStateVersion) fail(`reactionPlans[${position}].causationEventIds`, "invalid_reference", `invalid causation event ${eventId}`); } }); return true; }

export function validateDisplayPlanReferences(displayPlans, { inputRecords = [], claims = [], events = [], acceptedSpeechActs = [] } = {}) {
  const inputs = uniqueIndex(inputRecords, "inputRecordId", "inputRecords"), claimIndex = uniqueIndex(claims, "claimId", "claims"), eventIndex = uniqueIndex(events, "eventId", "events"), acts = uniqueIndex(acceptedSpeechActs, "speechActId", "acceptedSpeechActs");
  function spanFor(segment, plan) { if (segment.type === "raw_input") { if (segment.inputRecordId !== plan.inputRecordId) fail(`displayPlans.${plan.displayPlanId}`, "input_mismatch", "raw segment input must match plan"); return segment.sourceSpan; } const sourceObject = segment.claimId ? claimIndex.get(segment.claimId) : eventIndex.get(segment.voteEventId ?? segment.suspicionEventId); if (!sourceObject) fail(`displayPlans.${plan.displayPlanId}`, "dangling_reference", "canonical segment source does not exist"); if (sourceObject.source?.sourceType !== "player_accepted_act") fail(`displayPlans.${plan.displayPlanId}`, "ambiguous_display_source", "player display canonical source must derive from an accepted player act"); if (sourceObject.source.acceptedSpeechActIds && sourceObject.source.acceptedSpeechActIds.length !== 1) fail(`displayPlans.${plan.displayPlanId}`, "ambiguous_display_source", "canonical claim segment requires exactly one accepted source act"); const actId = sourceObject.source.acceptedSpeechActId ?? sourceObject.source.acceptedSpeechActIds[0], act = acts.get(actId); if (!act || act.inputRecordId !== plan.inputRecordId) fail(`displayPlans.${plan.displayPlanId}`, "ambiguous_display_source", "canonical segment source span cannot be resolved"); return act.sourceSpan; }
  displayPlans.forEach((plan, position) => { const input = inputs.get(plan.inputRecordId); if (!input || input.turnId !== plan.turnId) fail(`displayPlans[${position}].inputRecordId`, "invalid_reference", "display input and turn must match"); let previousEnd = -1; const used = new Set(); plan.segments.forEach((segment, segmentPosition) => { const span = spanFor(segment, plan), key = `${span.start}:${span.end}`; if (span.start < previousEnd) fail(`displayPlans[${position}].segments[${segmentPosition}]`, "source_order", "all segments must follow non-overlapping source order"); if (used.has(key)) fail(`displayPlans[${position}].segments[${segmentPosition}]`, "duplicate_source", "source span cannot be displayed twice"); used.add(key); previousEnd = span.end; if (span.end > [...input.rawText].length) fail(`displayPlans[${position}].segments[${segmentPosition}]`, "span_bounds", "source span exceeds raw input"); }); }); return true;
}

function publicationGroups(publications) { const groups = new Map(); publications.forEach((record) => { const records = groups.get(record.publicationId) ?? []; records.push(record); groups.set(record.publicationId, records); }); return groups; }
export function validatePersistedPublicationReferences(publications, { reactionPlans = [] } = {}) {
  const appendOrders = new Set(), slots = new Map(); let previousAppendOrder = -1;
  publications.forEach((record, position) => { if (!Number.isInteger(record.recordAppendOrder) || record.recordAppendOrder < 0 || appendOrders.has(record.recordAppendOrder) || record.recordAppendOrder <= previousAppendOrder) fail(`publications[${position}].recordAppendOrder`, "publication_order_conflict", "record append order must be unique and strictly ascending in input order"); appendOrders.add(record.recordAppendOrder); previousAppendOrder = record.recordAppendOrder; const owner = slots.get(record.publicationSlotOrder); if (owner && owner !== record.publicationId) fail(`publications[${position}].publicationSlotOrder`, "publication_order_conflict", "different publications cannot share a slot"); slots.set(record.publicationSlotOrder, record.publicationId); });
  uniqueIndex(publications.filter((record) => record.recordType === "npc_publication_reserved"), "reservationId", "reservations");
  uniqueIndex(publications.filter((record) => record.recordType === "npc_publication_finalized"), "finalizationId", "finalizations");
  const plans = uniqueIndex(reactionPlans, "reactionPlanId", "reactionPlans");
  for (const [publicationId, records] of publicationGroups(publications)) {
    const reservations = records.filter((record) => record.recordType === "npc_publication_reserved"), finalizations = records.filter((record) => record.recordType === "npc_publication_finalized"), canonical = records.filter((record) => record.recordType === "npc_canonical_published"), players = records.filter((record) => record.recordType === "player_utterance_published");
    if (reservations.length > 1 || finalizations.length > 1 || canonical.length > 1 || players.length > 1) fail(`publications.${publicationId}`, "duplicate_lifecycle_record", "publication lifecycle contains duplicate record types");
    if ((canonical.length || players.length) && records.length > 1) fail(`publications.${publicationId}`, "aggregate_conflict", "immediate publication cannot share a controlled lifecycle ID");
    if (finalizations.length && reservations.length !== 1) fail(`publications.${publicationId}`, "missing_reservation", "finalization requires exactly one reservation");
    if (reservations.length && finalizations.length) {
      const reservation = reservations[0], finalization = finalizations[0];
      for (const key of ["publicationId", "reservationId", "reactionPlanId", "actorId", "locale", "publicationSlotOrder"]) if (reservation[key] !== finalization[key]) fail(`publications.${publicationId}.${key}`, "lifecycle_mismatch", "reservation and finalization must agree");
      if (finalization.recordAppendOrder <= reservation.recordAppendOrder) fail(`publications.${publicationId}.recordAppendOrder`, "append_order", "finalization must append after reservation");
      const isFallback = fallbackReasons.has(finalization.finalizationReason); if ((finalization.finalizationReason === "renderer_selected" && finalization.fallbackUsed) || (isFallback && !finalization.fallbackUsed)) fail(`publications.${publicationId}.fallbackUsed`, "fallback_inconsistent", "fallback flag must match finalization reason");
      if (finalization.fallbackUsed && (finalization.selectedVariantId !== reservation.fallbackVariantId || finalization.selectedVariantVersion !== reservation.fallbackVariantVersion)) fail(`publications.${publicationId}.selectedVariantId`, "fallback_mismatch", "fallback finalization must preserve the reserved variant key and locale");
    }
    for (const record of records) if (record.reactionPlanId) { const plan = plans.get(record.reactionPlanId); if (plan && plan.locale !== record.locale) fail(`publications.${publicationId}.locale`, "locale_mismatch", "publication locale must match plan"); }
  }
  return true;
}

export function validatePublicationFinalizationAtAppend(finalization, { publications = [], pendingRendererRequests = [], registry = [], allowedVariants = [], expectedIntent } = {}) {
  validatePersistedPublicationReferences(publications);
  const attempt = classifyPublicationFinalizationAttempt({ candidate: finalization, existingFinalizations: publications.filter((record) => record.recordType === "npc_publication_finalized") });
  if (attempt.classification === "replay") return attempt;
  if (attempt.classification === "conflict") fail("finalization.publicationId", "idempotency_conflict", "publication was finalized with a different operation payload");
  const reservation = publications.find((record) => record.recordType === "npc_publication_reserved" && record.reservationId === finalization.reservationId), pending = pendingRendererRequests.find((record) => record.requestId === finalization.source.rendererRequestId);
  if (!reservation) fail("finalization.reservationId", "missing_reservation", "reservation must exist before finalization");
  for (const key of ["publicationId", "reservationId", "reactionPlanId", "actorId", "locale", "publicationSlotOrder"]) if (reservation[key] !== finalization[key]) fail(`finalization.${key}`, "lifecycle_mismatch", "finalization must match reservation");
  if (!pending) fail("finalization.source.rendererRequestId", "pending_request_mismatch", "matching PendingRendererRequest.requestId is required"); validatePendingRendererRequest(pending);
  if (pending.reactionPlanId !== finalization.reactionPlanId || pending.originatingInputRecordId !== reservation.originatingInputRecordId || pending.locale !== finalization.locale) fail("finalization.source.rendererRequestId", "pending_request_mismatch", "pending request must match reaction, origin, and locale");
  if (pending.status !== pendingStatusForReason[finalization.finalizationReason]) fail("finalization.finalizationReason", "pending_status_mismatch", "finalization reason and pending status are incompatible");
  const isFallback = fallbackReasons.has(finalization.finalizationReason);
  if ((finalization.finalizationReason === "renderer_selected" && finalization.fallbackUsed) || (isFallback && !finalization.fallbackUsed)) fail("finalization.fallbackUsed", "fallback_inconsistent", "fallback flag must match finalization reason");
  const selection = { variantId: finalization.selectedVariantId, variantVersion: finalization.selectedVariantVersion, locale: finalization.locale };
  if (isFallback) { if (finalization.selectedVariantId !== reservation.fallbackVariantId || finalization.selectedVariantVersion !== reservation.fallbackVariantVersion) fail("finalization.selectedVariantId", "fallback_inconsistent", "fallback finalization must use the reserved fallback key"); resolveHistoricalVariant(selection, registry); }
  else validateRendererSelection(selection, allowedVariants, registry, expectedIntent);
  return attempt;
}

export function validatePublicationReferences(publications, context = {}) { return validatePersistedPublicationReferences(publications, context); }

export function validatePlayerConversationCommitResultReferences(result, { inputRecords = [], displayPlans = [], publications = [], events = [], claims = [] } = {}) {
  const input = inputRecords.find((value) => value.inputRecordId === result.inputRecordId), plan = displayPlans.find((value) => value.displayPlanId === result.displayPlanId), publication = publications.find((value) => value.publicationId === result.playerPublicationId && value.recordType === "player_utterance_published");
  if (!input || !plan || !publication || input.requestId !== result.requestId || plan.inputRecordId !== input.inputRecordId || plan.stateVersion !== result.resultingStateVersion || publication.inputRecordId !== input.inputRecordId || publication.displayPlanId !== plan.displayPlanId || publication.requestId !== result.requestId || publication.correlationId !== result.correlationId || publication.turnId !== input.turnId || publication.gameStateVersion !== result.resultingStateVersion) fail("commitResult", "foreign_commit_object", "player commit references do not agree with one transaction");
  for (const eventId of result.createdEventIds) { const event = events.find((value) => value.eventId === eventId); if (!event || event.source.sourceType !== "player_accepted_act" || event.source.requestId !== result.requestId || event.source.inputRecordId !== result.inputRecordId || event.stateVersion !== result.resultingStateVersion) fail("commitResult.createdEventIds", "foreign_commit_object", `event ${eventId} does not belong to the player transaction`); }
  for (const claimId of result.createdClaimIds) { const claim = claims.find((value) => value.claimId === claimId); if (!claim || claim.source.sourceType !== "player_accepted_act" || claim.source.requestId !== result.requestId || claim.source.inputRecordId !== result.inputRecordId || claim.createdStateVersion !== result.resultingStateVersion) fail("commitResult.createdClaimIds", "foreign_commit_object", `claim ${claimId} does not belong to the player transaction`); }
  return true;
}
export function validateNpcReactionCommitResultReferences(result, { reactionPlans = [], publications = [], events = [], claims = [] } = {}) {
  const plan = reactionPlans.find((value) => value.reactionPlanId === result.reactionPlanId), expectedType = result.resultMode === "canonical_only" ? "npc_canonical_published" : "npc_publication_reserved", publication = publications.find((value) => value.publicationId === result.npcPublicationId && value.recordType === expectedType);
  if (!plan || !publication || plan.requestId !== result.requestId || plan.correlationId !== result.correlationId || plan.resultingStateVersion !== result.resultingStateVersion || publication.reactionPlanId !== plan.reactionPlanId || publication.reactionResultingStateVersion !== result.resultingStateVersion || (result.reservationId && publication.reservationId !== result.reservationId)) fail("commitResult", "foreign_commit_object", "NPC commit must reference its plan and same-commit publication/reservation");
  for (const eventId of result.createdEventIds) { const event = events.find((value) => value.eventId === eventId); if (!event || event.source.sourceType !== "npc_reaction" || event.source.reactionPlanId !== result.reactionPlanId || event.source.reactionCommitRequestId !== result.requestId || event.stateVersion !== result.resultingStateVersion) fail("commitResult.createdEventIds", "foreign_commit_object", `event ${eventId} does not belong to the NPC transaction`); }
  for (const claimId of result.createdClaimIds) { const claim = claims.find((value) => value.claimId === claimId); if (!claim || claim.source.sourceType !== "npc_reaction" || claim.source.reactionPlanId !== result.reactionPlanId || claim.source.reactionCommitRequestId !== result.requestId || claim.createdStateVersion !== result.resultingStateVersion) fail("commitResult.createdClaimIds", "foreign_commit_object", `claim ${claimId} does not belong to the NPC transaction`); }
  return true;
}
export function validateNpcPublicationFinalizationResultReferences(result, { publications = [] } = {}) { const finalization = publications.find((x) => x.recordType === "npc_publication_finalized" && x.finalizationId === result.finalizationId); if (!finalization) fail("finalizationResult.finalizationId", "dangling_reference", "stored finalization does not exist"); for (const key of ["publicationId", "reservationId", "reactionPlanId", "source", "locale", "selectedVariantId", "selectedVariantVersion", "fallbackUsed", "finalizationReason", "publicationSlotOrder", "recordAppendOrder", "createdAt"]) if (canonicalJson(finalization[key]) !== canonicalJson(result[key])) fail(`finalizationResult.${key}`, "result_mismatch", "result must exactly mirror stored finalization"); return true; }
export function validateCommitResultReferences(results, context = {}) { results.forEach((result) => result.commitType === "player_conversation" ? validatePlayerConversationCommitResultReferences(result, context) : validateNpcReactionCommitResultReferences(result, context)); return true; }

export function validateReferentialIntegrity(graph) { validateClaimReferences(graph.claims ?? [], graph); validateEventReferences(graph.events ?? [], graph); validateReactionPlanReferences(graph.reactionPlans ?? [], graph); validateDisplayPlanReferences(graph.displayPlans ?? [], graph); validatePersistedPublicationReferences(graph.publications ?? [], graph); validateCommitResultReferences(graph.commitResults ?? [], graph); return true; }
