import { canonicalJson } from "./ids.mjs";
import { resolveHistoricalVariant, validateRendererSelection } from "./canonicalRenderer.mjs";
import { ConversationValidationError, validateAcceptedSpeechAct, validateCanonicalClaim, validateConversationCommitResult, validateDisplayPublicationRecord, validateNpcPublicationFinalizationResult, validateNpcReactionPlan, validatePendingRendererRequest, validatePlayerInputRecord, validatePlayerUtteranceDisplayPlan, validatePublicEvent } from "./validators.mjs";

function fail(path, code, message) { throw new ConversationValidationError(path, code, message); }
function uniqueIndex(values, key, label) { const index = new Map(); values.forEach((value, position) => { const id = value[key]; if (index.has(id)) fail(`${label}[${position}].${key}`, "duplicate_id", `duplicate ${key} ${id}`); index.set(id, value); }); return index; }
function sameSource(left, right) {
  if (left?.sourceType !== right?.sourceType) return false;
  if (left.sourceType === "player_accepted_act") return right.acceptedSpeechActIds?.includes(left.acceptedSpeechActId);
  return left.reactionPlanId === right.reactionPlanId && left.descriptorId === right.descriptorId;
}
function claimPayload(claim) { return claim.type === "role_claim" ? { claimedRole: claim.claimedRole } : { targetId: claim.targetId, result: claim.result }; }
function sameSubject(left, right) { return left.actorId === right.actorId && left.type === right.type && (left.type === "role_claim" || left.targetId === right.targetId); }

const pendingStatusForReason = Object.freeze({ renderer_selected: "pending", renderer_timeout_fallback: "pending", renderer_error_fallback: "pending", renderer_invalid_output_fallback: "pending", renderer_abort_fallback: "aborting" });
const fallbackReasons = new Set(["renderer_timeout_fallback", "renderer_abort_fallback", "renderer_error_fallback", "renderer_invalid_output_fallback"]);
const finalizationIdentityFields = Object.freeze(["publicationId", "reservationId", "reactionPlanId", "source", "correlationId", "turnId", "stateVersion", "actorId", "locale", "selectedVariantId", "selectedVariantVersion", "fallbackUsed", "finalizationReason", "publicationSlotOrder"]);

export function classifyPublicationFinalizationAttempt({ candidate, existingFinalizations = [] }) {
  validateDisplayPublicationRecord(candidate); existingFinalizations.forEach(validateDisplayPublicationRecord);
  const existing = existingFinalizations.find((record) => record.publicationId === candidate.publicationId);
  if (!existing) return { classification: "new", existingFinalization: null, code: null };
  const identical = finalizationIdentityFields.every((key) => canonicalJson(existing[key]) === canonicalJson(candidate[key]));
  return identical ? { classification: "replay", existingFinalization: existing, code: "finalization_replay" } : { classification: "conflict", existingFinalization: existing, code: "idempotency_conflict" };
}

export function validateClaimReferences(claims, { acceptedSpeechActs = [], reactionPlans = [] } = {}) {
  const acts = uniqueIndex(acceptedSpeechActs, "speechActId", "acceptedSpeechActs"), plans = uniqueIndex(reactionPlans, "reactionPlanId", "reactionPlans"), claimIndex = uniqueIndex(claims, "claimId", "claims");
  claims.forEach((claim, position) => {
    if (claim.source.sourceType === "player_accepted_act") for (const actId of claim.source.acceptedSpeechActIds) { const act = acts.get(actId); if (!act || act.inputRecordId !== claim.source.inputRecordId || act.requestId !== claim.source.requestId || act.actorId !== claim.actorId) fail(`claims[${position}].source`, "invalid_reference", `invalid player claim source ${actId}`); const typeMatches = claim.type === "role_claim" ? act.type === "accepted_role_claim" : act.type === "accepted_result_claim", payloadMatches = claim.type === "role_claim" ? act.claimedRole === claim.claimedRole : act.targetId === claim.targetId && act.result === claim.result; if (!typeMatches) fail(`claims[${position}].source`, "claim_source_type_mismatch", "accepted speech act type does not match claim type"); if (!payloadMatches) fail(`claims[${position}].source`, "claim_source_payload_mismatch", "every accepted speech act must carry the canonical claim payload"); }
    else { const plan = plans.get(claim.source.reactionPlanId), descriptor = plan?.intendedSpeechActs.find((item) => item.descriptorId === claim.source.descriptorId); if (!plan || plan.npcId !== claim.actorId || plan.originatingInputRecordId !== claim.source.originatingInputRecordId || plan.requestId !== claim.source.reactionCommitRequestId || descriptor?.descriptorType !== claim.type) fail(`claims[${position}].source`, "claim_source_type_mismatch", "invalid NPC claim source or descriptor type"); const payloadMatches = claim.type === "role_claim" ? descriptor.claimedRole === claim.claimedRole : descriptor.targetId === claim.targetId && descriptor.result === claim.result; if (!payloadMatches) fail(`claims[${position}].source`, "claim_source_payload_mismatch", "reaction descriptor payload does not match claim payload"); }
    const repeat = claim.repeatsClaimId ? claimIndex.get(claim.repeatsClaimId) : null;
    if (repeat) { if (repeat.claimId === claim.claimId || repeat.createdStateVersion >= claim.createdStateVersion) fail(`claims[${position}].repeatsClaimId`, "future_reference", "repeat must reference a claim from a lower state version"); if (!sameSubject(claim, repeat) || canonicalJson(claimPayload(claim)) !== canonicalJson(claimPayload(repeat))) fail(`claims[${position}].repeatsClaimId`, "invalid_repeat", "repeat actor, type, subject, and payload must match"); }
    else if (claim.repeatsClaimId) fail(`claims[${position}].repeatsClaimId`, "dangling_reference", "repeat claim does not exist");
    for (const relatedId of claim.contradictsClaimIds) { const prior = claimIndex.get(relatedId); if (!prior) fail(`claims[${position}].contradictsClaimIds`, "dangling_reference", `claim ${relatedId} does not exist`); if (prior.claimId === claim.claimId || prior.createdStateVersion >= claim.createdStateVersion) fail(`claims[${position}].contradictsClaimIds`, "future_reference", "contradiction must reference a claim from a lower state version"); if (!sameSubject(claim, prior) || canonicalJson(claimPayload(claim)) === canonicalJson(claimPayload(prior))) fail(`claims[${position}].contradictsClaimIds`, "invalid_contradiction", "contradiction must have the same actor/type/subject and conflicting payload"); }
  }); return true;
}

const playerEventCompatibility = Object.freeze({ public_statement_recorded: "accepted_non_game_statement", public_question_recorded: "accepted_question", suspicion_expressed: "accepted_suspicion", vote_declared: "accepted_vote_declaration", role_claim_recorded: "accepted_role_claim", result_claim_recorded: "accepted_result_claim" });
const npcEventCompatibility = Object.freeze({ suspicion_expressed: "suspicion", vote_declared: "vote_declaration", role_claim_recorded: "role_claim", result_claim_recorded: "result_claim" });
export function validateEventReferences(events, { acceptedSpeechActs = [], reactionPlans = [], claims = [] } = {}) {
  const acts = uniqueIndex(acceptedSpeechActs, "speechActId", "acceptedSpeechActs"), plans = uniqueIndex(reactionPlans, "reactionPlanId", "reactionPlans"), claimIndex = uniqueIndex(claims, "claimId", "claims");
  const semanticEvents = new Map();
  events.forEach((event, position) => {
    if (event.source.sourceType === "player_accepted_act") { const act = acts.get(event.source.acceptedSpeechActId); if (!act || act.inputRecordId !== event.source.inputRecordId || act.requestId !== event.source.requestId || act.actorId !== event.actorId || act.acceptedPhase !== event.occurredPhase || act.type !== playerEventCompatibility[event.eventType] || event.requestId !== act.requestId || event.turnId !== act.acceptedTurnId || event.correlationId !== act.correlationId || event.stateVersion !== act.acceptedStateVersion + 1 || event.causationId !== act.causationId) fail(`events[${position}].source`, "incompatible_source", "event metadata must match its accepted speech act transaction"); const payloadMatches = act.type === "accepted_question" ? event.targetId === act.targetId && event.topic === act.topic : act.type === "accepted_suspicion" || act.type === "accepted_vote_declaration" ? event.targetId === act.targetId : true; if (!payloadMatches) fail(`events[${position}]`, "event_payload_mismatch", "event payload must match its accepted speech act"); }
    else { const plan = plans.get(event.source.reactionPlanId), descriptor = plan?.intendedSpeechActs.find((item) => item.descriptorId === event.source.descriptorId); if (!plan || plan.npcId !== event.actorId || plan.originatingInputRecordId !== event.source.originatingInputRecordId || plan.requestId !== event.source.reactionCommitRequestId || descriptor?.descriptorType !== npcEventCompatibility[event.eventType] || event.requestId !== plan.requestId || event.turnId !== plan.turnId || event.correlationId !== plan.correlationId || event.stateVersion !== plan.resultingStateVersion || event.causationId !== plan.causationId) fail(`events[${position}].source`, "incompatible_source", "event metadata must match its reaction plan transaction"); if ((descriptor.descriptorType === "suspicion" || descriptor.descriptorType === "vote_declaration") && event.targetId !== descriptor.targetId) fail(`events[${position}].targetId`, "event_payload_mismatch", "event target must match its reaction descriptor"); }
    if (event.claimId) { const claim = claimIndex.get(event.claimId), expected = event.eventType === "role_claim_recorded" ? "role_claim" : "result_claim"; if (!claim || claim.type !== expected || claim.actorId !== event.actorId || !sameSource(event.source, claim.source)) fail(`events[${position}].claimId`, "incompatible_claim", "claim event and canonical claim provenance must agree"); const sourceRequest = claim.source.requestId ?? claim.source.reactionCommitRequestId; if (event.requestId !== sourceRequest) fail(`events[${position}].requestId`, "request_mismatch", "event and claim request must match"); }
    const semanticKey = event.source.sourceType === "player_accepted_act" ? `${event.source.acceptedSpeechActId}\0${event.eventType}` : `${event.source.reactionPlanId}\0${event.source.descriptorId}\0${event.eventType}`, prior = semanticEvents.get(semanticKey); if (prior) { const comparable = (value) => { const { eventId: _eventId, createdOrder: _createdOrder, ...payload } = value; return payload; }; const same = canonicalJson(comparable(prior)) === canonicalJson(comparable(event)); fail(`events[${position}]`, same ? "duplicate_semantic_event" : "idempotency_conflict", same ? "semantic event key may be recorded at most once" : "semantic event key has a conflicting payload"); } semanticEvents.set(semanticKey, event);
  }); return true;
}

export function validateReactionPlanReferences(reactionPlans, { inputRecords = [], events = [], claims = [] } = {}) {
  const inputs = uniqueIndex(inputRecords, "inputRecordId", "inputRecords"), eventIndex = uniqueIndex(events, "eventId", "events"), claimIndex = uniqueIndex(claims, "claimId", "claims");
  reactionPlans.forEach((plan, position) => {
    const input = inputs.get(plan.originatingInputRecordId); if (!input || input.locale !== plan.locale || input.turnId !== plan.turnId || input.correlationId !== plan.correlationId) fail(`reactionPlans[${position}].originatingInputRecordId`, "invalid_reference", "originating input, locale, correlation, and turn must match"); if (plan.resultingStateVersion !== input.capturedStateVersion + 2) fail(`reactionPlans[${position}].resultingStateVersion`, "state_version_mismatch", "NPC reaction result must be originating input version plus two commits");
    for (const eventId of plan.causationEventIds) { const event = eventIndex.get(eventId); if (!event || event.stateVersion >= plan.resultingStateVersion) fail(`reactionPlans[${position}].causationEventIds`, "invalid_reference", `invalid causation event ${eventId}`); }
    for (const segment of plan.canonicalSegments ?? []) {
      const descriptor = plan.intendedSpeechActs.find((value) => value.descriptorId === segment.descriptorId), target = segment.claimId ? claimIndex.get(segment.claimId) : eventIndex.get(segment.voteEventId ?? segment.suspicionEventId); if (!target) fail(`reactionPlans[${position}].canonicalSegments`, "dangling_reference", "canonical segment target does not exist");
      const source = target.source, expectedEventType = segment.type === "canonical_vote" ? "vote_declared" : segment.type === "canonical_suspicion" ? "suspicion_expressed" : null;
      if (source?.sourceType !== "npc_reaction" || source.reactionPlanId !== plan.reactionPlanId || source.descriptorId !== segment.descriptorId || source.reactionCommitRequestId !== plan.requestId || target.actorId !== plan.npcId || (target.createdStateVersion ?? target.stateVersion) !== plan.resultingStateVersion || (expectedEventType && target.eventType !== expectedEventType) || (segment.type === "canonical_claim" && target.type !== descriptor.descriptorType)) fail(`reactionPlans[${position}].canonicalSegments`, "foreign_commit_object", "canonical segment target provenance must match plan and descriptor");
    }
  }); return true;
}

export function validateDisplayPlanReferences(displayPlans, { inputRecords = [], claims = [], events = [], acceptedSpeechActs = [] } = {}) {
  const inputs = uniqueIndex(inputRecords, "inputRecordId", "inputRecords"), claimIndex = uniqueIndex(claims, "claimId", "claims"), eventIndex = uniqueIndex(events, "eventId", "events"), acts = uniqueIndex(acceptedSpeechActs, "speechActId", "acceptedSpeechActs");
  function spanFor(segment, plan) { if (segment.type === "raw_input") { if (segment.inputRecordId !== plan.inputRecordId) fail(`displayPlans.${plan.displayPlanId}`, "input_mismatch", "raw segment input must match plan"); return segment.sourceSpan; } const sourceObject = segment.claimId ? claimIndex.get(segment.claimId) : eventIndex.get(segment.voteEventId ?? segment.suspicionEventId); if (!sourceObject) fail(`displayPlans.${plan.displayPlanId}`, "dangling_reference", "canonical segment source does not exist"); if (sourceObject.source?.sourceType !== "player_accepted_act") fail(`displayPlans.${plan.displayPlanId}`, "ambiguous_display_source", "player display canonical source must derive from an accepted player act"); if (sourceObject.source.acceptedSpeechActIds && sourceObject.source.acceptedSpeechActIds.length !== 1) fail(`displayPlans.${plan.displayPlanId}`, "ambiguous_display_source", "canonical claim segment requires exactly one accepted source act"); const actId = sourceObject.source.acceptedSpeechActId ?? sourceObject.source.acceptedSpeechActIds[0], act = acts.get(actId); if (!act || act.inputRecordId !== plan.inputRecordId) fail(`displayPlans.${plan.displayPlanId}`, "ambiguous_display_source", "canonical segment source span cannot be resolved"); return act.sourceSpan; }
  displayPlans.forEach((plan, position) => { const input = inputs.get(plan.inputRecordId); if (!input || input.turnId !== plan.turnId) fail(`displayPlans[${position}].inputRecordId`, "invalid_reference", "display input and turn must match"); let previousEnd = 0; const used = new Set(); plan.segments.forEach((segment, segmentPosition) => { const span = spanFor(segment, plan), key = `${span.start}:${span.end}`; if (span.start !== previousEnd) fail(`displayPlans[${position}].segments[${segmentPosition}]`, "source_coverage", "segments must be contiguous from the beginning of raw input"); if (used.has(key)) fail(`displayPlans[${position}].segments[${segmentPosition}]`, "duplicate_source", "source span cannot be displayed twice"); used.add(key); previousEnd = span.end; if (span.end > [...input.rawText].length) fail(`displayPlans[${position}].segments[${segmentPosition}]`, "span_bounds", "source span exceeds raw input"); }); if (previousEnd !== [...input.rawText].length) fail(`displayPlans[${position}].segments`, "source_coverage", "segments must cover the complete raw input"); }); return true;
}

function publicationGroups(publications) { const groups = new Map(); publications.forEach((record) => { const records = groups.get(record.publicationId) ?? []; records.push(record); groups.set(record.publicationId, records); }); return groups; }
export function validatePersistedPublicationReferences(publications, { reactionPlans = [] } = {}) {
  publications.forEach(validateDisplayPublicationRecord); reactionPlans.forEach(validateNpcReactionPlan);
  const appendOrders = new Set(), slots = new Map(); let previousAppendOrder = -1;
  publications.forEach((record, position) => { if (!Number.isInteger(record.recordAppendOrder) || record.recordAppendOrder < 0 || appendOrders.has(record.recordAppendOrder) || record.recordAppendOrder <= previousAppendOrder) fail(`publications[${position}].recordAppendOrder`, "publication_order_conflict", "record append order must be unique and strictly ascending in input order"); appendOrders.add(record.recordAppendOrder); previousAppendOrder = record.recordAppendOrder; const owner = slots.get(record.publicationSlotOrder); if (owner && owner !== record.publicationId) fail(`publications[${position}].publicationSlotOrder`, "publication_order_conflict", "different publications cannot share a slot"); slots.set(record.publicationSlotOrder, record.publicationId); });
  uniqueIndex(publications.filter((record) => record.recordType === "npc_publication_reserved"), "reservationId", "reservations");
  uniqueIndex(publications.filter((record) => record.recordType === "npc_publication_finalized"), "finalizationId", "finalizations");
  const plans = uniqueIndex(reactionPlans, "reactionPlanId", "reactionPlans");
  for (const [publicationId, records] of publicationGroups(publications)) {
    const reservations = records.filter((record) => record.recordType === "npc_publication_reserved"), finalizations = records.filter((record) => record.recordType === "npc_publication_finalized"), canonical = records.filter((record) => record.recordType === "npc_canonical_published"), players = records.filter((record) => record.recordType === "player_utterance_published");
    if (reservations.length > 1 || finalizations.length > 1 || canonical.length > 1 || players.length > 1) fail(`publications.${publicationId}`, "duplicate_lifecycle_record", "publication lifecycle contains duplicate record types");
    if ((canonical.length || players.length) && records.length > 1) fail(`publications.${publicationId}`, "aggregate_conflict", "immediate publication cannot share a controlled lifecycle ID");
    if (finalizations.length && reservations.length !== 1) fail(`publications.${publicationId}`, "missing_reservation", "finalization requires exactly one reservation");
    if (reservations.length && finalizations.length) {
      const reservation = reservations[0], finalization = finalizations[0];
      for (const key of ["publicationId", "reservationId", "reactionPlanId", "actorId", "locale", "publicationSlotOrder"]) if (reservation[key] !== finalization[key]) fail(`publications.${publicationId}.${key}`, "lifecycle_mismatch", "reservation and finalization must agree");
      if (finalization.recordAppendOrder <= reservation.recordAppendOrder) fail(`publications.${publicationId}.recordAppendOrder`, "append_order", "finalization must append after reservation");
      if (finalization.stateVersion !== reservation.reactionResultingStateVersion) fail(`publications.${publicationId}.stateVersion`, "state_version_mismatch", "finalization state version must equal reservation reaction version");
      const isFallback = fallbackReasons.has(finalization.finalizationReason); if ((finalization.finalizationReason === "renderer_selected" && finalization.fallbackUsed) || (isFallback && !finalization.fallbackUsed)) fail(`publications.${publicationId}.fallbackUsed`, "fallback_inconsistent", "fallback flag must match finalization reason");
      if (finalization.fallbackUsed && (finalization.selectedVariantId !== reservation.fallbackVariantId || finalization.selectedVariantVersion !== reservation.fallbackVariantVersion)) fail(`publications.${publicationId}.selectedVariantId`, "fallback_mismatch", "fallback finalization must preserve the reserved variant key and locale");
    }
    for (const record of records) if (record.reactionPlanId) {
      const plan = plans.get(record.reactionPlanId); if (!plan) fail(`publications.${publicationId}.reactionPlanId`, "dangling_reference", "publication reaction plan does not exist");
      const expectedMode = record.recordType === "npc_canonical_published" ? "canonical_only" : "controlled_commentary"; if (plan.renderMode !== expectedMode || record.correlationId !== plan.correlationId || record.turnId !== plan.turnId || record.actorId !== plan.npcId || record.locale !== plan.locale) fail(`publications.${publicationId}`, "foreign_commit_object", "publication metadata must match its reaction plan");
      if (record.recordType !== "npc_publication_finalized" && (record.reactionCommitRequestId !== plan.requestId || record.originatingInputRecordId !== plan.originatingInputRecordId || record.reactionResultingStateVersion !== plan.resultingStateVersion)) fail(`publications.${publicationId}`, "foreign_commit_object", "publication commit metadata must match its reaction plan");
      if (record.recordType === "npc_publication_finalized" && record.stateVersion !== plan.resultingStateVersion) fail(`publications.${publicationId}.stateVersion`, "state_version_mismatch", "finalization state version must equal plan resulting version");
      if (record.recordType === "npc_canonical_published" && canonicalJson(record.canonicalSegmentIds) !== canonicalJson(plan.canonicalSegments.map((segment) => segment.segmentId))) fail(`publications.${publicationId}.canonicalSegmentIds`, "foreign_commit_object", "canonical publication must cover the plan segment set in order");
    }
  }
  return true;
}

export function validatePublicationFinalizationAtAppend(finalization, { publications = [], reactionPlans = [], pendingRendererRequests = [], registry = [], allowedVariants = [], expectedIntent } = {}) {
  validateDisplayPublicationRecord(finalization); validatePersistedPublicationReferences(publications, { reactionPlans });
  const reservation = publications.find((record) => record.recordType === "npc_publication_reserved" && record.reservationId === finalization.reservationId), reactionPlan = reactionPlans.find((plan) => plan.reactionPlanId === finalization.reactionPlanId);
  if (!reservation) fail("finalization.reservationId", "missing_reservation", "reservation must exist before finalization");
  if (!reactionPlan) fail("finalization.reactionPlanId", "dangling_reference", "reaction plan must exist before finalization");
  for (const key of ["publicationId", "reservationId", "reactionPlanId", "actorId", "locale", "publicationSlotOrder"]) if (reservation[key] !== finalization[key]) fail(`finalization.${key}`, "lifecycle_mismatch", "finalization must match reservation");
  if (finalization.stateVersion !== reservation.reactionResultingStateVersion || finalization.stateVersion !== reactionPlan.resultingStateVersion) fail("finalization.stateVersion", "state_version_mismatch", "candidate version must directly match reservation and reaction plan");
  const attempt = classifyPublicationFinalizationAttempt({ candidate: finalization, existingFinalizations: publications.filter((record) => record.recordType === "npc_publication_finalized") });
  if (attempt.classification === "replay") return attempt;
  if (attempt.classification === "conflict") fail("finalization.publicationId", "idempotency_conflict", "publication was finalized with a different operation payload");
  const pending = pendingRendererRequests.find((record) => record.requestId === finalization.source.rendererRequestId);
  if (!pending) fail("finalization.source.rendererRequestId", "pending_request_mismatch", "matching PendingRendererRequest.requestId is required"); validatePendingRendererRequest(pending);
  if (pending.reactionPlanId !== finalization.reactionPlanId || pending.originatingInputRecordId !== reservation.originatingInputRecordId || pending.locale !== finalization.locale || pending.resultingStateVersion !== finalization.stateVersion || pending.turnId !== finalization.turnId || pending.targetNpcId !== finalization.actorId || pending.correlationId !== finalization.correlationId || pending.correlationId !== reservation.correlationId || pending.correlationId !== reactionPlan.correlationId || pending.causationId !== reactionPlan.reactionPlanId) fail("finalization.source.rendererRequestId", "pending_request_mismatch", "pending request must match reaction, origin, locale, version, turn, actor, correlation, and causation");
  if (pending.status !== pendingStatusForReason[finalization.finalizationReason]) fail("finalization.finalizationReason", "pending_status_mismatch", "finalization reason and pending status are incompatible");
  const isFallback = fallbackReasons.has(finalization.finalizationReason);
  if ((finalization.finalizationReason === "renderer_selected" && finalization.fallbackUsed) || (isFallback && !finalization.fallbackUsed)) fail("finalization.fallbackUsed", "fallback_inconsistent", "fallback flag must match finalization reason");
  const selection = { variantId: finalization.selectedVariantId, variantVersion: finalization.selectedVariantVersion, locale: finalization.locale };
  if (isFallback) { if (finalization.selectedVariantId !== reservation.fallbackVariantId || finalization.selectedVariantVersion !== reservation.fallbackVariantVersion) fail("finalization.selectedVariantId", "fallback_inconsistent", "fallback finalization must use the reserved fallback key"); resolveHistoricalVariant(selection, registry); }
  else validateRendererSelection(selection, allowedVariants, registry, expectedIntent);
  return attempt;
}

export function validatePublicationReferences(publications, context = {}) { return validatePersistedPublicationReferences(publications, context); }

export function validatePlayerPublicationReferences(publications, { inputRecords = [], displayPlans = [], acceptedSpeechActs = [] } = {}) {
  const inputs = uniqueIndex(inputRecords, "inputRecordId", "inputRecords"), plans = uniqueIndex(displayPlans, "displayPlanId", "displayPlans"), inputOwners = new Set(), planOwners = new Set();
  publications.filter((record) => record.recordType === "player_utterance_published").forEach((record, position) => { const input = inputs.get(record.inputRecordId), plan = plans.get(record.displayPlanId), acts = acceptedSpeechActs.filter((act) => act.inputRecordId === record.inputRecordId); if (!input || !plan) fail(`playerPublications[${position}]`, "dangling_reference", "player publication input and display plan must exist"); if (inputOwners.has(record.inputRecordId) || planOwners.has(record.displayPlanId)) fail(`playerPublications[${position}]`, "duplicate_publication_owner", "input and display plan may each have exactly one player publication"); inputOwners.add(record.inputRecordId); planOwners.add(record.displayPlanId); if (plan.inputRecordId !== input.inputRecordId || plan.turnId !== input.turnId || record.requestId !== input.requestId || record.correlationId !== input.correlationId || record.turnId !== input.turnId || record.actorId !== input.actorId || record.gameStateVersion !== plan.stateVersion || plan.stateVersion !== input.capturedStateVersion + 1) fail(`playerPublications[${position}]`, "foreign_commit_object", "player publication metadata and resulting version must match input and display plan"); if (acts.length < 1 || acts.some((act) => act.acceptedPhase !== record.occurredPhase) || new Set(acts.map((act) => act.acceptedPhase)).size !== 1) fail(`playerPublications[${position}].occurredPhase`, "foreign_commit_object", "publication phase must match every accepted act for its input"); }); return true;
}

export function validatePlayerConversationCommitResultReferences(result, { inputRecords = [], displayPlans = [], publications = [], events = [], claims = [] } = {}) {
  const input = inputRecords.find((value) => value.inputRecordId === result.inputRecordId), plan = displayPlans.find((value) => value.displayPlanId === result.displayPlanId), publication = publications.find((value) => value.publicationId === result.playerPublicationId && value.recordType === "player_utterance_published");
  if (!input || !plan || !publication || input.requestId !== result.requestId || input.correlationId !== result.correlationId || input.capturedStateVersion !== result.preconditionStateVersion || plan.inputRecordId !== input.inputRecordId || plan.stateVersion !== result.resultingStateVersion || publication.inputRecordId !== input.inputRecordId || publication.displayPlanId !== plan.displayPlanId || publication.requestId !== result.requestId || publication.correlationId !== result.correlationId || publication.turnId !== input.turnId || publication.actorId !== input.actorId || publication.gameStateVersion !== result.resultingStateVersion) fail("commitResult", "foreign_commit_object", "player commit references do not agree with one transaction");
  for (const eventId of result.createdEventIds) { const event = events.find((value) => value.eventId === eventId); if (!event || event.source.sourceType !== "player_accepted_act" || event.source.requestId !== result.requestId || event.source.inputRecordId !== result.inputRecordId || event.stateVersion !== result.resultingStateVersion) fail("commitResult.createdEventIds", "foreign_commit_object", `event ${eventId} does not belong to the player transaction`); }
  for (const claimId of result.createdClaimIds) { const claim = claims.find((value) => value.claimId === claimId); if (!claim || claim.source.sourceType !== "player_accepted_act" || claim.source.requestId !== result.requestId || claim.source.inputRecordId !== result.inputRecordId || claim.createdStateVersion !== result.resultingStateVersion) fail("commitResult.createdClaimIds", "foreign_commit_object", `claim ${claimId} does not belong to the player transaction`); }
  const ownedEvents = events.filter((event) => event.source.sourceType === "player_accepted_act" && event.source.requestId === result.requestId && event.source.inputRecordId === result.inputRecordId && event.stateVersion === result.resultingStateVersion).map((event) => event.eventId).sort(), ownedClaims = claims.filter((claim) => claim.source.sourceType === "player_accepted_act" && claim.source.requestId === result.requestId && claim.source.inputRecordId === result.inputRecordId && claim.createdStateVersion === result.resultingStateVersion).map((claim) => claim.claimId).sort();
  if (canonicalJson([...result.createdEventIds].sort()) !== canonicalJson(ownedEvents) || canonicalJson([...result.createdClaimIds].sort()) !== canonicalJson(ownedClaims)) fail("commitResult", "foreign_commit_object", "created object IDs must exactly equal the transaction-owned object sets"); return true;
}
export function validateNpcReactionCommitResultReferences(result, { reactionPlans = [], publications = [], events = [], claims = [] } = {}) {
  const plan = reactionPlans.find((value) => value.reactionPlanId === result.reactionPlanId), expectedType = result.resultMode === "canonical_only" ? "npc_canonical_published" : "npc_publication_reserved", publication = publications.find((value) => value.publicationId === result.npcPublicationId && value.recordType === expectedType);
  if (!plan || !publication || plan.renderMode !== result.resultMode || plan.requestId !== result.requestId || plan.correlationId !== result.correlationId || plan.resultingStateVersion !== result.resultingStateVersion || publication.reactionPlanId !== plan.reactionPlanId || publication.reactionCommitRequestId !== result.requestId || publication.originatingInputRecordId !== plan.originatingInputRecordId || publication.correlationId !== result.correlationId || publication.turnId !== plan.turnId || publication.actorId !== plan.npcId || publication.locale !== plan.locale || publication.reactionResultingStateVersion !== result.resultingStateVersion || (result.reservationId && publication.reservationId !== result.reservationId)) fail("commitResult", "foreign_commit_object", "NPC commit must reference its plan and same-commit publication/reservation");
  if (publication.recordType === "npc_canonical_published" && canonicalJson(publication.canonicalSegmentIds) !== canonicalJson(plan.canonicalSegments.map((segment) => segment.segmentId))) fail("commitResult.npcPublicationId", "foreign_commit_object", "canonical publication segment set must match plan");
  for (const eventId of result.createdEventIds) { const event = events.find((value) => value.eventId === eventId); if (!event || event.source.sourceType !== "npc_reaction" || event.source.reactionPlanId !== result.reactionPlanId || event.source.reactionCommitRequestId !== result.requestId || event.stateVersion !== result.resultingStateVersion) fail("commitResult.createdEventIds", "foreign_commit_object", `event ${eventId} does not belong to the NPC transaction`); }
  for (const claimId of result.createdClaimIds) { const claim = claims.find((value) => value.claimId === claimId); if (!claim || claim.source.sourceType !== "npc_reaction" || claim.source.reactionPlanId !== result.reactionPlanId || claim.source.reactionCommitRequestId !== result.requestId || claim.createdStateVersion !== result.resultingStateVersion) fail("commitResult.createdClaimIds", "foreign_commit_object", `claim ${claimId} does not belong to the NPC transaction`); }
  const ownedEvents = events.filter((event) => event.source.sourceType === "npc_reaction" && event.source.reactionPlanId === result.reactionPlanId && event.source.reactionCommitRequestId === result.requestId && event.stateVersion === result.resultingStateVersion).map((event) => event.eventId).sort(), ownedClaims = claims.filter((claim) => claim.source.sourceType === "npc_reaction" && claim.source.reactionPlanId === result.reactionPlanId && claim.source.reactionCommitRequestId === result.requestId && claim.createdStateVersion === result.resultingStateVersion).map((claim) => claim.claimId).sort();
  if (canonicalJson([...result.createdEventIds].sort()) !== canonicalJson(ownedEvents) || canonicalJson([...result.createdClaimIds].sort()) !== canonicalJson(ownedClaims)) fail("commitResult", "foreign_commit_object", "created object IDs must exactly equal the transaction-owned object sets"); return true;
}
export function validateNpcPublicationFinalizationResultReferences(result, { publications = [] } = {}) { const finalization = publications.find((x) => x.recordType === "npc_publication_finalized" && x.finalizationId === result.finalizationId); if (!finalization) fail("finalizationResult.finalizationId", "dangling_reference", "stored finalization does not exist"); for (const key of ["publicationId", "reservationId", "reactionPlanId", "source", "locale", "selectedVariantId", "selectedVariantVersion", "fallbackUsed", "finalizationReason", "publicationSlotOrder", "recordAppendOrder", "createdAt"]) if (canonicalJson(finalization[key]) !== canonicalJson(result[key])) fail(`finalizationResult.${key}`, "result_mismatch", "result must exactly mirror stored finalization"); return true; }
export function validateCommitResultReferences(results, context = {}) { const requests = new Map(), orders = new Set(); results.forEach((result, index) => { const prior = requests.get(result.requestId); if (prior) fail(`commitResults[${index}].requestId`, prior.requestFingerprint === result.requestFingerprint ? "duplicate_commit_result" : "idempotency_conflict", "request ID may have exactly one persisted commit result"); requests.set(result.requestId, result); if (orders.has(result.createdAtOrder)) fail(`commitResults[${index}].createdAtOrder`, "duplicate_order", "commit result order must be unique"); orders.add(result.createdAtOrder); }); results.forEach((result) => result.commitType === "player_conversation" ? validatePlayerConversationCommitResultReferences(result, context) : validateNpcReactionCommitResultReferences(result, context)); return true; }

export function validateConversationGraph(graph) {
  const inputs = graph.inputRecords ?? [];
  inputs.forEach(validatePlayerInputRecord);
  uniqueIndex(inputs, "createdOrder", "inputRecords"); uniqueIndex(graph.events ?? [], "createdOrder", "events");
  (graph.acceptedSpeechActs ?? []).forEach((act, index) => { const input = inputs.find((value) => value.inputRecordId === act.inputRecordId); if (!input) fail(`acceptedSpeechActs[${index}].inputRecordId`, "dangling_reference", "accepted act input does not exist"); validateAcceptedSpeechAct(act, input.rawText, `acceptedSpeechActs[${index}]`); if (act.requestId !== input.requestId || act.correlationId !== input.correlationId || act.acceptedTurnId !== input.turnId || act.acceptedStateVersion !== input.capturedStateVersion || act.actorId !== input.actorId) fail(`acceptedSpeechActs[${index}]`, "foreign_commit_object", "accepted act transaction metadata must match its input record"); });
  (graph.claims ?? []).forEach((claim, index) => validateCanonicalClaim(claim, `claims[${index}]`));
  (graph.events ?? []).forEach((event, index) => validatePublicEvent(event, `events[${index}]`));
  (graph.reactionPlans ?? []).forEach(validateNpcReactionPlan);
  (graph.displayPlans ?? []).forEach((plan, index) => { const input = inputs.find((value) => value.inputRecordId === plan.inputRecordId); if (!input) fail(`displayPlans[${index}].inputRecordId`, "dangling_reference", "display input does not exist"); validatePlayerUtteranceDisplayPlan(plan, input); });
  (graph.publications ?? []).forEach(validateDisplayPublicationRecord);
  (graph.commitResults ?? []).forEach(validateConversationCommitResult);
  (graph.finalizationResults ?? []).forEach(validateNpcPublicationFinalizationResult);
  validateClaimReferences(graph.claims ?? [], graph); validateEventReferences(graph.events ?? [], graph); validateReactionPlanReferences(graph.reactionPlans ?? [], graph); validateDisplayPlanReferences(graph.displayPlans ?? [], graph); validatePersistedPublicationReferences(graph.publications ?? [], graph); validatePlayerPublicationReferences(graph.publications ?? [], graph); validateCommitResultReferences(graph.commitResults ?? [], graph); const finalizationIds = new Set(), finalizationPublications = new Set(); (graph.finalizationResults ?? []).forEach((result, index) => { if (finalizationIds.has(result.finalizationId) || finalizationPublications.has(result.publicationId)) fail(`finalizationResults[${index}]`, "duplicate_finalization_result", "finalization result identity must be unique"); finalizationIds.add(result.finalizationId); finalizationPublications.add(result.publicationId); validateNpcPublicationFinalizationResultReferences(result, graph); }); return true;
}
export const validateReferentialIntegrity = validateConversationGraph;
