import assert from "node:assert/strict";
import test from "node:test";
import { WerewolfGame } from "../src/gameEngine.mjs";
import { appendBrowserPublicationNode, deliverPlayerPublication, deliverProjectedEntries, retryPlayerPublicationAcknowledgement, writeCliPublication } from "../src/playerDisplaySink.mjs";
import { PlayerPublicationDeliveryController } from "../src/playerPublicationDelivery.mjs";

function ids() { let value = 0; return () => String(++value); }
function interpreter() { return { async interpretPlayerInput(request) { return { schemaVersion: 1, requestId: request.requestId, correlationId: request.correlationId, serverCorrelationId: "server-1", result: { schemaVersion: 1, requestId: request.requestId, correlationId: request.correlationId, modelOutput: { schemaVersion: 1, alternatives: [{ alternativeId: "alternative-1", confidence: 1, speechActs: [{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }] }] }, diagnostics: { providerName: "test", model: "test", attemptCount: 1, elapsedMs: 0 } } }; } }; }
function game(options = {}) { return WerewolfGame.create({ seed: 1, scenario: "sample", shuffleRoles: false, createId: ids(), interpreterValidationEnabled: true, playerConversationCommitEnabled: true, playerStructuredConsumerEnabled: true, interpreterProvider: interpreter(), responseProvider: { async generateResponse() { return { text: "response", providerName: "test", model: "test", usage: null, notes: [] }; } }, ...options }); }
async function action(instance = game()) { return { instance, result: await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }) }; }
function authoritative(instance) { return structuredClone({ stateVersion: instance.state.stateVersion, turnId: instance.state.turnId, turnOrder: instance.state.turnOrder, phase: instance.state.phase, conversation: instance.state.conversation, playerLog: instance.state.playerLog, players: instance.state.players }); }

test("delivery state machine requires sink success receipt and never mutates authoritative state", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], before = authoritative(instance), attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "prepared"); assert.deepEqual(authoritative(instance), before);
  assert.throws(() => instance.getPlayerPublicationSinkReceipt({ publicationId }), (error) => error.code === "publication_not_delivered"); const capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "in_flight"); assert.throws(() => instance.acknowledgePlayerPublication({}), (error) => error.code === "invalid_sink_success_receipt");
  const receipt = instance.completePlayerPublicationSink(capability); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "sink_succeeded"); const acknowledged = instance.acknowledgePlayerPublication(receipt); assert.equal(acknowledged.status, "acknowledged"); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "acknowledged"); assert.deepEqual(authoritative(instance), before);
});

test("publication resolution failure becomes terminal for the session", () => {
  let id = 0; const controller = new PlayerPublicationDeliveryController({ gameSessionId: "game-1", createId: () => String(++id), enabled: true, listPublications: () => [{ publicationId: "publication-1", publicationSlotOrder: 0 }], resolvePublication() { const error = new Error("compatibility_mapping_conflict"); error.code = "compatibility_mapping_conflict"; throw error; } }); assert.throws(() => controller.prepare({ publicationId: "publication-1", consumerId: "browser", sinkType: "browser" }), (error) => error.code === "compatibility_mapping_conflict"); assert.equal(controller.stateFor("publication-1"), "failed_terminal"); assert.throws(() => controller.prepare({ publicationId: "publication-1", consumerId: "browser", sinkType: "browser" }), (error) => error.code === "compatibility_mapping_conflict");
});

test("sink failure is retryable and successful retry reuses the authoritative publication", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], before = authoritative(instance), first = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "cli", sinkType: "cli" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: first.deliveryAttemptId }); instance.failPlayerPublicationSink(capability); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "failed_retryable"); assert.equal(instance.getPlayerPublicationDeliveryCandidates().includes(publicationId), true);
  let writes = 0; await deliverPlayerPublication({ game: instance, publicationId, consumerId: "cli", sinkType: "cli", write: async () => { writes += 1; } }); assert.equal(writes, 1); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "acknowledged"); assert.deepEqual(authoritative(instance), before);
});

test("duplicate acknowledgement is idempotent and emits exactly one observer event per invocation", async () => {
  const events = [], instance = game({ playerStructuredConsumerObserver: (entry) => events.push(entry) }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = instance.completePlayerPublicationSink(capability), first = instance.acknowledgePlayerPublication(receipt), second = instance.acknowledgePlayerPublication(receipt); assert.equal(first, second); assert.equal(events.filter((entry) => entry.outcomeCategory === "publication_acknowledged").length, 1); assert.equal(events.filter((entry) => entry.outcomeCategory === "duplicate_ack_suppressed").length, 1);
});

test("observer failure preserves acknowledgement and ack-only retry never rewrites the sink", async () => {
  const instance = game({ playerStructuredConsumerObserver() { throw new Error("observer"); } }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0]; let writes = 0; await deliverPlayerPublication({ game: instance, publicationId, consumerId: "browser", sinkType: "browser", write: async () => { writes += 1; } }); const duplicate = retryPlayerPublicationAcknowledgement({ game: instance, publicationId }); assert.equal(duplicate.status, "acknowledged"); assert.equal(writes, 1);
});

test("sink success followed by acknowledgement failure retries acknowledgement only", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], acknowledge = instance.acknowledgePlayerPublication.bind(instance); let firstAck = true, writes = 0; instance.acknowledgePlayerPublication = (receipt) => { if (firstAck) { firstAck = false; const error = new Error("ack transport"); throw error; } return acknowledge(receipt); };
  await assert.rejects(deliverPlayerPublication({ game: instance, publicationId, consumerId: "browser", sinkType: "browser", write: async () => { writes += 1; } }), (error) => error.acknowledgementOnlyRetry === true); const resultAck = retryPlayerPublicationAcknowledgement({ game: instance, publicationId }); assert.equal(resultAck.status, "acknowledged"); assert.equal(writes, 1);
});

test("wrong receipt, reset receipt, generation switch, and concurrent attempts fail closed", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }); assert.throws(() => instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), (error) => error.code === "publication_not_prepared"); assert.throws(() => { instance.playerStructuredConsumerEnabled = false; instance._syncStructuredConsumerMode(); }, (error) => error.code === "consumer_mode_switch_in_flight"); const receipt = instance.completePlayerPublicationSink(capability); instance.destroy(); assert.throws(() => instance.acknowledgePlayerPublication(receipt), (error) => error.code === "stale_publication_session");
});

test("prepared attempt becomes stale after a quiescent consumer generation switch", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "cli", sinkType: "cli" }); instance.playerStructuredConsumerEnabled = false; instance._syncStructuredConsumerMode(); assert.throws(() => instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), (error) => error.code === "stale_consumer_generation");
});

test("ON to OFF rollback never redisplays an acknowledged legacy player entry", async () => {
  const { instance, result } = await action(); await deliverProjectedEntries({ game: instance, entries: result.playerFacingEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} }); instance.playerStructuredConsumerEnabled = false; const rollback = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(rollback.playerFacingEntries.some((entry) => entry.phase === "player_question"), false); assert.equal(instance.state.conversation.publications.length, 1);
});

test("get_state, history projection, diagnostics, and replay do not start delivery", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0]; assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen"); await instance.dispatchPlayerAction({ type: "get_state" }); instance.getDeveloperDiagnostics(); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen"); const record = instance.state.conversation.idempotencyRecords[0]; await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen");
});

test("browser-like DOM and CLI sinks write exactly once, fail without ack, and sanitize output", async () => {
  const fakeDocument = { createElement() { return { className: "", dataset: {}, textContent: "", children: [], append(...children) { this.children.push(...children); } }; } }, container = { children: [], append(node) { this.children.push(node); } };
  const browser = await action(), browserEntry = browser.result.playerFacingEntries.find((entry) => entry.structured); await deliverProjectedEntries({ game: browser.instance, entries: [browserEntry], consumerId: "browser", sinkType: "browser", writeStructured: async (entry) => appendBrowserPublicationNode({ document: fakeDocument, container, entry }), writeLegacy: async () => {} }); assert.equal(container.children.length, 1); assert.equal(container.children[0].dataset.publicationId, browserEntry.publicationId); assert.equal(container.children[0].children[1].textContent, "hello");
  const cli = await action(), cliEntry = cli.result.playerFacingEntries.find((entry) => entry.structured), output = []; await deliverProjectedEntries({ game: cli.instance, entries: [cliEntry], consumerId: "cli", sinkType: "cli", writeStructured: async (entry) => writeCliPublication({ entry, write: async (text) => output.push(text) }), writeLegacy: async () => {} }); assert.equal(output.length, 1); assert.equal(output[0].endsWith("hello"), true); const sanitized = []; await writeCliPublication({ entry: { ...cliEntry, message: "a\u001bb" }, write: async (text) => sanitized.push(text) }); assert.equal(sanitized[0].endsWith("a[control]b"), true);
  const failed = await action(); await assert.rejects(deliverPlayerPublication({ game: failed.instance, publicationId: failed.result.deliveryPublicationIds[0], consumerId: "browser", sinkType: "browser", write: async () => { throw new Error("append failed"); } }), /append failed/); assert.notEqual(failed.instance.playerPublicationDeliveryController.stateFor(failed.result.deliveryPublicationIds[0]), "acknowledged");
});
