import assert from "node:assert/strict";
import test from "node:test";
import { WerewolfGame } from "../src/gameEngine.mjs";
import { appendBrowserPublicationNode, consumeLiveActionDisplay, deliverLivePlayerEntries, deliverPlayerPublication, retryPlayerPublicationAcknowledgement, sinkReceiptIdentity, writeCliPublication } from "../src/playerDisplaySink.mjs";
import { PlayerPublicationDeliveryController } from "../src/playerPublicationDelivery.mjs";

function ids() { let value = 0; return () => String(++value); }
function interpreter() { return { async interpretPlayerInput(request) { return { schemaVersion: 1, requestId: request.requestId, correlationId: request.correlationId, serverCorrelationId: "server-1", result: { schemaVersion: 1, requestId: request.requestId, correlationId: request.correlationId, modelOutput: { schemaVersion: 1, alternatives: [{ alternativeId: "alternative-1", confidence: 1, speechActs: [{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }] }] }, diagnostics: { providerName: "test", model: "test", attemptCount: 1, elapsedMs: 0 } } }; } }; }
function game(options = {}) { return WerewolfGame.create({ seed: 1, scenario: "sample", shuffleRoles: false, createId: ids(), interpreterValidationEnabled: true, playerConversationCommitEnabled: true, playerStructuredConsumerEnabled: true, interpreterProvider: interpreter(), responseProvider: { async generateResponse() { return { text: "response", providerName: "test", model: "test", usage: null, notes: [] }; } }, ...options }); }
async function action(instance = game()) { return { instance, result: await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }) }; }
function authoritative(instance) { return structuredClone({ stateVersion: instance.state.stateVersion, turnId: instance.state.turnId, turnOrder: instance.state.turnOrder, phase: instance.state.phase, conversation: instance.state.conversation, playerLog: instance.state.playerLog, players: instance.state.players }); }

test("delivery state machine requires sink success receipt and never mutates authoritative state", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], before = authoritative(instance), attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "prepared"); assert.deepEqual(authoritative(instance), before);
  assert.throws(() => instance.getPlayerPublicationSinkReceipt({ publicationId }), (error) => error.code === "invalid_sink_success_receipt"); const capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "in_flight"); assert.throws(() => instance.acknowledgePlayerPublication({}), (error) => error.code === "invalid_sink_success_receipt");
  const receipt = instance.completePlayerPublicationSink(capability); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "sink_succeeded"); const acknowledged = instance.acknowledgePlayerPublication(receipt); assert.equal(acknowledged.status, "acknowledged"); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "acknowledged"); assert.deepEqual(authoritative(instance), before);
});

test("publication resolution failure becomes terminal for the session", () => {
  let id = 0; const controller = new PlayerPublicationDeliveryController({ gameSessionId: "game-1", createId: () => String(++id), enabled: true, listPublications: () => [{ publicationId: "publication-1", publicationSlotOrder: 0 }], resolvePublication() { const error = new Error("compatibility_mapping_conflict"); error.code = "compatibility_mapping_conflict"; throw error; } }); assert.throws(() => controller.prepare({ publicationId: "publication-1", consumerId: "browser", sinkType: "browser" }), (error) => error.code === "compatibility_mapping_conflict"); assert.equal(controller.stateFor("publication-1"), "failed_terminal"); assert.throws(() => controller.prepare({ publicationId: "publication-1", consumerId: "browser", sinkType: "browser" }), (error) => error.code === "compatibility_mapping_conflict");
});

test("sink failure is retryable and successful retry reuses the authoritative publication", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], before = authoritative(instance), first = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "cli", sinkType: "cli" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: first.deliveryAttemptId }); instance.failPlayerPublicationSink(capability); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "failed_retryable"); assert.equal(instance.getPlayerPublicationDeliveryCandidates().includes(publicationId), true);
  let writes = 0; await deliverPlayerPublication({ game: instance, publicationId, consumerId: "cli", sinkType: "cli", write: async () => { writes += 1; } }); assert.equal(writes, 1); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "acknowledged"); assert.deepEqual(authoritative(instance), before);
});

test("duplicate acknowledgement is idempotent and emits exactly one observer event per invocation", async () => {
  const events = [], instance = game({ playerStructuredConsumerObserver: (entry) => events.push(entry) }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = instance.completePlayerPublicationSink(capability), first = instance.acknowledgePlayerPublication(receipt), second = instance.acknowledgePlayerPublication(receipt); assert.equal(first, second); assert.equal(events.filter((entry) => entry.outcomeCategory === "publication_acknowledged").length, 1); assert.equal(events.filter((entry) => entry.outcomeCategory === "duplicate_ack_suppressed").length, 1);
});

test("observer failure preserves acknowledgement and ack-only retry never rewrites the sink", async () => {
  const instance = game({ playerStructuredConsumerObserver() { throw new Error("observer"); } }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0]; let writes = 0, identity; await deliverPlayerPublication({ game: instance, publicationId, consumerId: "browser", sinkType: "browser", write: async () => { writes += 1; }, onSinkSucceeded: (value) => { identity = value; } }); const duplicate = retryPlayerPublicationAcknowledgement({ game: instance, deliveryIdentity: identity }); assert.equal(duplicate.status, "acknowledged"); assert.equal(writes, 1);
});

test("sink success followed by acknowledgement failure retries acknowledgement only", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], acknowledge = instance.acknowledgePlayerPublication.bind(instance); let firstAck = true, writes = 0; instance.acknowledgePlayerPublication = (receipt) => { if (firstAck) { firstAck = false; const error = new Error("ack transport"); throw error; } return acknowledge(receipt); };
  let identity; await assert.rejects(deliverPlayerPublication({ game: instance, publicationId, consumerId: "browser", sinkType: "browser", write: async () => { writes += 1; }, onSinkSucceeded: (value) => { identity = value; } }), (error) => error.acknowledgementOnlyRetry === true); const resultAck = retryPlayerPublicationAcknowledgement({ game: instance, deliveryIdentity: identity }); assert.equal(resultAck.status, "acknowledged"); assert.equal(writes, 1);
});

test("wrong receipt, reset receipt, generation switch, and concurrent attempts fail closed", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }); assert.throws(() => instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), (error) => error.code === "publication_not_prepared"); assert.throws(() => { instance.playerStructuredConsumerEnabled = false; instance._syncStructuredConsumerMode(); }, (error) => error.code === "consumer_mode_switch_in_flight"); const receipt = instance.completePlayerPublicationSink(capability); instance.destroy(); assert.throws(() => instance.acknowledgePlayerPublication(receipt), (error) => error.code === "stale_publication_session");
});

test("prepared attempt becomes stale after a quiescent consumer generation switch", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "cli", sinkType: "cli" }); instance.playerStructuredConsumerEnabled = false; instance._syncStructuredConsumerMode(); assert.throws(() => instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), (error) => error.code === "stale_consumer_generation");
});

test("ON to OFF rollback never redisplays an acknowledged legacy player entry", async () => {
  const { instance, result } = await action(); await deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} }); instance.playerStructuredConsumerEnabled = false; const rollback = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(rollback.playerFacingEntries.filter((entry) => entry.structured).length, 1); assert.deepEqual(rollback.livePlayerDisplayEntries, []); assert.equal(instance.state.conversation.publications.length, 1);
});

test("get_state, history projection, diagnostics, and replay do not start delivery", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0]; assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen"); await instance.dispatchPlayerAction({ type: "get_state" }); instance.getDeveloperDiagnostics(); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen"); const record = instance.state.conversation.idempotencyRecords[0]; await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen");
});

test("browser-like DOM and CLI sinks write exactly once, fail without ack, and sanitize output", async () => {
  const fakeDocument = { createElement() { return { className: "", dataset: {}, textContent: "", children: [], append(...children) { this.children.push(...children); } }; } }, container = { children: [], append(node) { this.children.push(node); } };
  const browser = await action(), browserEntry = browser.result.playerFacingEntries.find((entry) => entry.structured); await deliverLivePlayerEntries({ game: browser.instance, entries: browser.result.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery"), consumerId: "browser", sinkType: "browser", writeStructured: async (entry) => appendBrowserPublicationNode({ document: fakeDocument, container, entry }), writeLegacy: async () => {} }); assert.equal(container.children.length, 1); assert.equal(container.children[0].dataset.publicationId, browserEntry.publicationId); assert.equal(container.children[0].children[1].textContent, "hello");
  const cli = await action(), cliEntry = cli.result.playerFacingEntries.find((entry) => entry.structured), output = []; await deliverLivePlayerEntries({ game: cli.instance, entries: cli.result.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery"), consumerId: "cli", sinkType: "cli", writeStructured: async (entry) => writeCliPublication({ entry, write: async (text) => output.push(text) }), writeLegacy: async () => {} }); assert.equal(output.length, 1); assert.equal(output[0].endsWith("hello"), true); const sanitized = []; await writeCliPublication({ entry: { ...cliEntry, message: "a\u001bb" }, write: async (text) => sanitized.push(text) }); assert.equal(sanitized[0].endsWith("a[control]b"), true);
  const failed = await action(); await assert.rejects(deliverPlayerPublication({ game: failed.instance, publicationId: failed.result.deliveryPublicationIds[0], consumerId: "browser", sinkType: "browser", write: async () => { throw new Error("append failed"); } }), /append failed/); assert.notEqual(failed.instance.playerPublicationDeliveryController.stateFor(failed.result.deliveryPublicationIds[0]), "acknowledged");
});

test("history results and replay never become live delivery envelopes", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], record = instance.state.conversation.idempotencyRecords[0];
  const replayUnacknowledged = await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint, logCursor: 0 }); assert.equal(replayUnacknowledged.playerFacingEntries.some((entry) => entry.publicationId === publicationId), true); assert.deepEqual(replayUnacknowledged.livePlayerDisplayEntries, []); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen");
  await deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} });
  const replayAcknowledged = await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint, logCursor: 0 }), state = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(replayAcknowledged.playerFacingEntries.filter((entry) => entry.publicationId === publicationId).length, 1); assert.deepEqual(replayAcknowledged.livePlayerDisplayEntries, []); assert.deepEqual(state.livePlayerDisplayEntries, []);
  const historyAgain = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.deepEqual(historyAgain.playerFacingEntries, state.playerFacingEntries); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "acknowledged");
});

test("normal stale cursor suppresses acknowledged delivery while preserving mixed history order", async () => {
  const { instance, result } = await action(); await deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} }); instance.state.phase = "day_discussion";
  const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), oldPublication = result.deliveryPublicationIds[0]; assert.equal(next.playerFacingEntries.filter((entry) => entry.publicationId === oldPublication).length, 1); assert.equal(next.livePlayerDisplayEntries.some((entry) => entry.publicationId === oldPublication), false); assert.deepEqual(next.livePlayerDisplayEntries.slice(-2).map((entry) => entry.kind), ["player_publication_delivery", "legacy_display"]);
});

test("sink writes only the frozen controller-prepared payload", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], seen = [];
  await deliverPlayerPublication({ game: instance, publicationId, consumerId: "browser", sinkType: "browser", displayEntry: { publicationId: "other", day: 99, phase: "night", message: "forged" }, write: async (entry) => { seen.push(entry); assert.equal(Object.isFrozen(entry), true); } });
  assert.equal(seen[0].publicationId, publicationId); assert.equal(seen[0].message, "hello"); assert.notEqual(seen[0].day, 99); assert.notEqual(seen[0].phase, "night");
});

test("sink receipt lookup requires the complete exact delivery identity", async () => {
  const events = [], instance = game({ playerStructuredConsumerObserver: (event) => events.push(event) }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser-exact", sinkType: "browser" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = instance.completePlayerPublicationSink(capability), identity = sinkReceiptIdentity(receipt);
  assert.equal(instance.getPlayerPublicationSinkReceipt(identity), receipt);
  for (const [field, value, code] of [["consumerId", "wrong", "publication_not_delivered"], ["consumerGeneration", identity.consumerGeneration + 1, "stale_consumer_generation"], ["deliveryAttemptId", "wrong", "publication_not_delivered"], ["sinkType", "cli", "publication_not_delivered"], ["deliveryMode", "legacy", "publication_not_delivered"], ["gameSessionId", "wrong", "stale_publication_session"], ["receiptId", "wrong", "publication_not_delivered"]]) assert.throws(() => instance.getPlayerPublicationSinkReceipt({ ...identity, [field]: value }), (error) => error.code === code);
  assert.throws(() => instance.getPlayerPublicationSinkReceipt({ publicationId }), (error) => error.code === "invalid_sink_success_receipt"); assert.throws(() => instance.acknowledgePlayerPublication(structuredClone(receipt)), (error) => error.code === "invalid_sink_success_receipt"); assert.deepEqual(events.filter((event) => event.outcomeCategory === "stale_ack_rejected").map((event) => event.reasonCode), ["stale_consumer_generation", "stale_publication_session"]);
});

test("cutover blocks live backfill without truncating structured history", async () => {
  const instance = game({ playerStructuredConsumerEnabled: false }), old = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), oldPublication = instance.state.conversation.publications[0].publicationId; assert.equal(old.livePlayerDisplayEntries.some((entry) => entry.preCutoverPublicationId === oldPublication), true); await consumeLiveActionDisplay({ game: instance, action: old, consumerId: "browser-main", sinkType: "browser", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => {} });
  instance.state.phase = "day_discussion"; instance.playerStructuredConsumerEnabled = true; const cutoverRead = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(cutoverRead.playerFacingEntries.filter((entry) => entry.publicationId === oldPublication).length, 1); assert.deepEqual(cutoverRead.livePlayerDisplayEntries, []);
  const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), newPublication = instance.state.conversation.publications.at(-1).publicationId; assert.equal(next.livePlayerDisplayEntries.some((entry) => entry.publicationId === oldPublication), false); assert.equal(next.livePlayerDisplayEntries.some((entry) => entry.publicationId === newPublication), true);
});

test("combined browser and CLI action paths use only the live envelope and exact bookkeeping", async () => {
  const fakeDocument = { createElement() { return { className: "", dataset: {}, textContent: "", children: [], append(...children) { this.children.push(...children); } }; } }, container = { children: [], append(node) { this.children.push(node); } }, browser = await action(), browserBookkeeping = new Map(), browserHistory = [];
  await consumeLiveActionDisplay({ game: browser.instance, action: browser.result, consumerId: "browser-main", sinkType: "browser", bookkeeping: browserBookkeeping, writeStructured: async (entry) => { browserHistory.push(entry); return appendBrowserPublicationNode({ document: fakeDocument, container, entry }); }, writeLegacy: async (entry) => browserHistory.push(entry) }); assert.equal(container.children.length, 1); assert.equal(browserHistory.length, 2); const browserIdentity = [...browserBookkeeping.values()][0].identity; assert.equal(browserIdentity.receiptId, container.children[0].dataset.receiptId); browser.instance.destroy(); assert.throws(() => retryPlayerPublicationAcknowledgement({ game: browser.instance, deliveryIdentity: browserIdentity }), (error) => error.code === "stale_publication_session");
  const cli = await action(), cliBookkeeping = new Map(), output = [], cliHistory = []; await consumeLiveActionDisplay({ game: cli.instance, action: cli.result, consumerId: "cli-main", sinkType: "cli", bookkeeping: cliBookkeeping, writeStructured: async (entry) => { cliHistory.push(entry); return writeCliPublication({ entry, write: async (text) => output.push(text) }); }, writeLegacy: async (entry) => cliHistory.push(entry) }); assert.equal(output.length, 1); assert.equal(cliHistory.length, 2); assert.equal([...cliBookkeeping.values()][0].identity.consumerId, "cli-main"); const historyOnly = await cli.instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); await consumeLiveActionDisplay({ game: cli.instance, action: historyOnly, consumerId: "cli-main", sinkType: "cli", bookkeeping: cliBookkeeping, writeStructured: async () => { throw new Error("history reached sink"); }, writeLegacy: async () => { throw new Error("history reached sink"); } }); assert.equal(output.length, 1); assert.equal(cliHistory.length, 2);
});

test("failed sink remains pending across replay and cursor advance", async () => {
  const { instance, result } = await action(), oldPublication = result.deliveryPublicationIds[0], record = instance.state.conversation.idempotencyRecords[0]; await assert.rejects(deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => { throw new Error("sink failed"); }, writeLegacy: async () => {} }), /sink failed/);
  const replay = await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint, logCursor: instance.state.playerLog.length }); assert.deepEqual(replay.livePlayerDisplayEntries, []); instance.state.phase = "day_discussion";
  const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), playerEnvelopes = next.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery"); assert.equal(playerEnvelopes[0].publicationId, oldPublication); assert.equal(playerEnvelopes.length, 2); assert.equal(next.livePlayerDisplayEntries.at(-1).kind, "legacy_display");
});

test("ack-only pending survives cursor advance and retries without another sink write", async () => {
  const { instance, result } = await action(), bookkeeping = new Map(), acknowledge = instance.acknowledgePlayerPublication.bind(instance); let failures = 2, writes = 0; instance.acknowledgePlayerPublication = (receipt) => { if (failures-- > 0) throw new Error("ack unavailable"); return acknowledge(receipt); };
  await assert.rejects(consumeLiveActionDisplay({ game: instance, action: result, consumerId: "browser-main", sinkType: "browser", bookkeeping, writeStructured: async () => { writes += 1; }, writeLegacy: async () => {} }), /ack unavailable/); assert.equal(writes, 1); const state = await instance.dispatchPlayerAction({ type: "get_state", logCursor: instance.state.playerLog.length }); assert.deepEqual(state.livePlayerDisplayEntries, []); instance.state.phase = "day_discussion";
  const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }); assert.equal(next.livePlayerDisplayEntries[0].acknowledgementOnly, true); await consumeLiveActionDisplay({ game: instance, action: next, consumerId: "browser-main", sinkType: "browser", bookkeeping, writeStructured: async () => { writes += 1; }, writeLegacy: async () => {} }); assert.equal(writes, 2); assert.equal(instance.playerPublicationDeliveryController.stateFor(result.deliveryPublicationIds[0]), "acknowledged");
});

test("ON to OFF delivers unseen, retryable, and new publications through legacy acknowledgement", async () => {
  const instance = game(), first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }), oldPublication = first.deliveryPublicationIds[0]; await assert.rejects(deliverLivePlayerEntries({ game: instance, entries: first.livePlayerDisplayEntries, consumerId: "cli-main", sinkType: "cli", writeStructured: async () => { throw new Error("structured sink failed"); }, writeLegacy: async () => {} }), /structured sink failed/); instance.playerStructuredConsumerEnabled = false; instance.state.phase = "day_discussion";
  const rollback = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), legacyPlayers = rollback.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery"); assert.equal(legacyPlayers.length, 2); assert.equal(legacyPlayers.every((entry) => entry.deliveryMode === "legacy"), true); assert.equal(legacyPlayers[0].publicationId, oldPublication);
  const visible = [], before = authoritative(instance); await consumeLiveActionDisplay({ game: instance, action: rollback, consumerId: "cli-main", sinkType: "cli", bookkeeping: new Map(), writeStructured: async () => { throw new Error("structured writer used"); }, writeLegacy: async (entry) => visible.push(entry) }); assert.equal(visible.filter((entry) => entry.phase === "player_question").length, 2); assert.equal(instance.playerPublicationDeliveryController.stateFor(oldPublication), "acknowledged"); assert.equal(rollback.playerFacingEntries.filter((entry) => entry.structured).length, 1); assert.deepEqual(authoritative(instance), before);
  const unseen = game(), unseenFirst = await unseen.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }), unseenPublication = unseenFirst.deliveryPublicationIds[0]; unseen.playerStructuredConsumerEnabled = false; unseen.state.phase = "day_discussion"; const unseenRollback = await unseen.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: unseen.state.playerLog.length }); assert.equal(unseenRollback.livePlayerDisplayEntries.some((entry) => entry.publicationId === unseenPublication && entry.deliveryMode === "legacy"), true);
});

test("stale acknowledgement observer uses one redacted outcome per invocation", async () => {
  const events = [], instance = game({ playerStructuredConsumerObserver: (event) => events.push(event) }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser", deliveryMode: "structured" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = instance.completePlayerPublicationSink(capability); instance.destroy(); assert.throws(() => instance.acknowledgePlayerPublication(receipt), (error) => error.code === "stale_publication_session"); assert.deepEqual(events.filter((event) => event.outcomeCategory === "stale_ack_rejected").map((event) => event.reasonCode), ["stale_publication_session"]);
  const isolated = game({ playerStructuredConsumerObserver() { throw new Error("observer"); } }), isolatedAction = await action(isolated), isolatedAttempt = isolated.preparePlayerPublicationDelivery({ publicationId: isolatedAction.result.deliveryPublicationIds[0], consumerId: "cli", sinkType: "cli", deliveryMode: "structured" }), isolatedCapability = isolated.beginPlayerPublicationSink({ deliveryAttemptId: isolatedAttempt.deliveryAttemptId }), isolatedReceipt = isolated.completePlayerPublicationSink(isolatedCapability); isolated.destroy(); assert.throws(() => isolated.acknowledgePlayerPublication(isolatedReceipt), (error) => error.code === "stale_publication_session");
});

test("rejected in-flight mode switch is atomic and retries after acknowledgement", async () => {
  for (const sinkType of ["browser", "cli"]) { const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: `${sinkType}-main`, sinkType, deliveryMode: "structured" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), generation = instance.playerPublicationDeliveryController.consumerGeneration, watermark = instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder; instance.playerStructuredConsumerEnabled = false;
    assert.throws(() => instance._syncStructuredConsumerMode(), (error) => error.code === "consumer_mode_switch_in_flight"); assert.equal(instance._consumerModeObserved, true); assert.equal(instance.playerPublicationDeliveryController.enabled, true); assert.equal(instance.playerPublicationDeliveryController.consumerGeneration, generation); assert.equal(instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder, watermark); const receipt = instance.completePlayerPublicationSink(capability); instance.acknowledgePlayerPublication(receipt); instance.state.phase = "day_discussion";
    const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }); assert.equal(instance._consumerModeObserved, false); assert.equal(instance.playerPublicationDeliveryController.enabled, false); assert.equal(next.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery").every((entry) => entry.deliveryMode === "legacy"), true); const visible = []; await consumeLiveActionDisplay({ game: instance, action: next, consumerId: `${sinkType}-main`, sinkType, bookkeeping: new Map(), writeStructured: async () => { throw new Error("wrong mode"); }, writeLegacy: async (entry) => visible.push(entry) }); assert.equal(visible.filter((entry) => entry.phase === "player_question").length, 1); }
});

test("pre-cutover legacy-delivered publications never redisplay after rollback", async () => {
  for (const sinkType of ["browser", "cli"]) { const instance = game({ playerStructuredConsumerEnabled: false }), old = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), oldPublication = instance.state.conversation.publications[0].publicationId, initialVisible = []; await consumeLiveActionDisplay({ game: instance, action: old, consumerId: `${sinkType}-main`, sinkType, bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async (entry) => initialVisible.push(entry) }); assert.equal(initialVisible.filter((entry) => entry.phase === "player_question").length, 1); assert.equal(instance.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds().has(oldPublication), true);
    instance.playerStructuredConsumerEnabled = true; await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); instance.playerStructuredConsumerEnabled = false; instance.state.phase = "day_discussion"; const rollback = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }); assert.equal(rollback.livePlayerDisplayEntries.some((entry) => entry.publicationId === oldPublication), false); assert.equal(rollback.playerFacingEntries.filter((entry) => entry.publicationId === oldPublication).length, 1); assert.equal(rollback.livePlayerDisplayEntries.filter((entry) => entry.kind === "legacy_display").every((entry) => entry.entry.phase !== "player_question" || entry.entry.message !== old.playerFacingEntries.find((entry) => entry.phase === "player_question")?.message), true); }
  const failed = game({ playerStructuredConsumerEnabled: false }), failedAction = await failed.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), failedPublication = failed.state.conversation.publications[0].publicationId; await assert.rejects(consumeLiveActionDisplay({ game: failed, action: failedAction, consumerId: "browser-main", sinkType: "browser", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async (entry) => { if (entry.phase === "player_question") throw new Error("legacy sink failed"); } }), /legacy sink failed/); assert.equal(failed.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds().has(failedPublication), false);
});

test("first cutover watermark survives repeated cycles and partial acknowledgement", async () => {
  const instance = game(), first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }), firstPublication = first.deliveryPublicationIds[0], watermark = instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder; await assert.rejects(deliverLivePlayerEntries({ game: instance, entries: first.livePlayerDisplayEntries, consumerId: "browser-main", sinkType: "browser", writeStructured: async () => { throw new Error("sink failed"); }, writeLegacy: async () => {} }), /sink failed/);
  instance.playerStructuredConsumerEnabled = false; instance._syncStructuredConsumerMode(); instance.playerStructuredConsumerEnabled = true; instance._syncStructuredConsumerMode(); assert.equal(instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder, watermark); instance.state.phase = "day_discussion"; const second = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), secondPublication = instance.state.conversation.publications.at(-1).publicationId; assert.equal(second.deliveryPublicationIds.includes(firstPublication), true); await consumeLiveActionDisplay({ game: instance, action: { ...second, livePlayerDisplayEntries: second.livePlayerDisplayEntries.filter((entry) => entry.publicationId === firstPublication) }, consumerId: "browser-main", sinkType: "browser", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => {} });
  instance.playerStructuredConsumerEnabled = false; instance._syncStructuredConsumerMode(); instance.state.phase = "day_discussion"; const duringOff = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), offPublication = instance.state.conversation.publications.at(-1).publicationId; instance.playerStructuredConsumerEnabled = true; instance._syncStructuredConsumerMode(); instance.state.phase = "day_discussion"; const final = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }); assert.equal(instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder, watermark); assert.equal(final.deliveryPublicationIds.includes(firstPublication), false); assert.equal(final.deliveryPublicationIds.includes(secondPublication), true); assert.equal(final.deliveryPublicationIds.includes(offPublication), true); assert.equal(duringOff.deliveryPublicationIds.includes(offPublication), true);
});

test("new controller observes valid old-session identity and receipt exactly once", () => {
  let id = 0; const publication = { publicationId: "publication-old", publicationSlotOrder: 0 }, old = new PlayerPublicationDeliveryController({ gameSessionId: "session-old", createId: () => String(++id), enabled: true, listPublications: () => [publication], resolvePublication: () => Object.freeze({ message: "safe" }) }), attempt = old.prepare({ publicationId: publication.publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "structured" }), capability = old.begin({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = old.complete(capability), identity = sinkReceiptIdentity(receipt), events = [], next = new PlayerPublicationDeliveryController({ gameSessionId: "session-new", createId: () => String(++id), observer: (event) => events.push(event), enabled: true, listPublications: () => [], resolvePublication: () => null });
  assert.throws(() => next.receiptFor(identity), (error) => error.code === "stale_publication_session"); assert.deepEqual(events.map((event) => [event.outcomeCategory, event.reasonCode]), [["stale_ack_rejected", "stale_publication_session"]]); assert.throws(() => next.acknowledge(receipt), (error) => error.code === "stale_publication_session"); assert.equal(events.filter((event) => event.outcomeCategory === "stale_ack_rejected").length, 2); const forged = Object.freeze({ ...receipt, gameSessionId: "session-new", receiptId: "forged-current" }); assert.throws(() => next.acknowledge(forged), (error) => error.code === "invalid_sink_success_receipt"); assert.equal(events.length, 2);
  const isolated = new PlayerPublicationDeliveryController({ gameSessionId: "session-new", createId: () => String(++id), observer() { throw new Error("observer"); }, enabled: true, listPublications: () => [], resolvePublication: () => null }); assert.throws(() => isolated.receiptFor(identity), (error) => error.code === "stale_publication_session");
});

test("terminal resolution failure persists across modes and clears only with a new session", async () => {
  const structured = await action(), publicationId = structured.result.deliveryPublicationIds[0], originalResolve = structured.instance.playerPublicationDeliveryController.resolvePublication; structured.instance.playerPublicationDeliveryController.resolvePublication = () => { const error = new Error("structured terminal"); error.code = "structured_terminal_failure"; throw error; }; assert.throws(() => structured.instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "structured" }), (error) => error.code === "structured_terminal_failure"); structured.instance.playerStructuredConsumerEnabled = false; structured.instance._syncStructuredConsumerMode(); assert.equal(structured.instance.getPlayerPublicationDeliveryCandidates().includes(publicationId), false); assert.throws(() => structured.instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "legacy" }), (error) => error.code === "structured_terminal_failure"); structured.instance.playerStructuredConsumerEnabled = true; structured.instance._syncStructuredConsumerMode(); assert.equal(structured.instance.getPlayerPublicationDeliveryCandidates().includes(publicationId), false); assert.throws(() => structured.instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "structured" }), (error) => error.code === "structured_terminal_failure");
  const legacy = await action(); legacy.instance.playerStructuredConsumerEnabled = false; legacy.instance._syncStructuredConsumerMode(); const legacyPublication = legacy.result.deliveryPublicationIds[0]; legacy.instance.playerPublicationDeliveryController.resolvePublication = () => { const error = new Error("legacy terminal"); error.code = "legacy_terminal_failure"; throw error; }; assert.throws(() => legacy.instance.preparePlayerPublicationDelivery({ publicationId: legacyPublication, consumerId: "cli-main", sinkType: "cli", deliveryMode: "legacy" }), (error) => error.code === "legacy_terminal_failure"); legacy.instance.playerStructuredConsumerEnabled = true; legacy.instance._syncStructuredConsumerMode(); assert.equal(legacy.instance.getPlayerPublicationDeliveryCandidates().includes(legacyPublication), false); assert.throws(() => legacy.instance.preparePlayerPublicationDelivery({ publicationId: legacyPublication, consumerId: "cli-main", sinkType: "cli", deliveryMode: "structured" }), (error) => error.code === "legacy_terminal_failure");
  const reset = await action(); reset.instance.playerPublicationDeliveryController.resolvePublication = originalResolve; assert.equal(reset.instance.playerPublicationDeliveryController.stateFor(reset.result.deliveryPublicationIds[0]), "unseen");
});

test("first cutover rejects undelivered legacy publications until cursor-independent retry succeeds", async () => {
  for (const sinkType of ["browser", "cli"]) { const instance = game({ playerStructuredConsumerEnabled: false }), first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), firstPublication = instance.state.conversation.publications[0].publicationId; await assert.rejects(consumeLiveActionDisplay({ game: instance, action: first, consumerId: `${sinkType}-main`, sinkType, bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async (entry) => { if (entry.phase === "player_question") throw new Error("legacy sink failed"); } }), /legacy sink failed/); const before = { enabled: instance.playerPublicationDeliveryController.enabled, generation: instance.playerPublicationDeliveryController.consumerGeneration, watermark: instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder, delivered: [...instance.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds()], authoritative: authoritative(instance) }; instance.playerStructuredConsumerEnabled = true; assert.throws(() => instance._syncStructuredConsumerMode(), (error) => error.code === "pre_cutover_delivery_pending"); assert.equal(instance._consumerModeObserved, false); assert.equal(instance.playerPublicationDeliveryController.enabled, before.enabled); assert.equal(instance.playerPublicationDeliveryController.consumerGeneration, before.generation); assert.equal(instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder, before.watermark); assert.deepEqual([...instance.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds()], before.delivered); assert.deepEqual(authoritative(instance), before.authoritative);
    instance.playerStructuredConsumerEnabled = false; instance.state.phase = "day_discussion"; const retry = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), playerEnvelopes = retry.livePlayerDisplayEntries.filter((entry) => entry.preCutoverPublicationId); assert.equal(playerEnvelopes[0].preCutoverPublicationId, firstPublication); assert.equal(playerEnvelopes.length, 2); let playerWrite = 0; await assert.rejects(consumeLiveActionDisplay({ game: instance, action: retry, consumerId: `${sinkType}-main`, sinkType, bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async (entry) => { if (entry.phase === "player_question" && ++playerWrite === 2) throw new Error("partial legacy sink failed"); } }), /partial legacy sink failed/); assert.equal(instance.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds().has(firstPublication), true); instance.playerStructuredConsumerEnabled = true; assert.throws(() => instance._syncStructuredConsumerMode(), (error) => error.code === "pre_cutover_delivery_pending"); instance.playerStructuredConsumerEnabled = false; instance.state.phase = "day_discussion";
    const finalRetry = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), unresolved = finalRetry.livePlayerDisplayEntries.filter((entry) => entry.preCutoverPublicationId); assert.equal(unresolved.length, 2); await consumeLiveActionDisplay({ game: instance, action: finalRetry, consumerId: `${sinkType}-main`, sinkType, bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => {} }); instance.playerStructuredConsumerEnabled = true; const cutover = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(instance.playerPublicationDeliveryController.enabled, true); assert.deepEqual(cutover.livePlayerDisplayEntries, []); assert.equal(cutover.playerFacingEntries.filter((entry) => entry.structured).length, 3); assert.equal(cutover.playerFacingEntries.filter((entry) => entry.publicationId === firstPublication).length, 1); }
});
