import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { WerewolfGame } from "../src/gameEngine.mjs";
import { createPhase3Binding } from "../src/interpreterValidation.mjs";
import { preparePlayerConversationCommit } from "../src/playerConversationCommit.mjs";
import { projectMappedPlayerEntries, renderPlayerPublication, renderUnacknowledgedPlayerPublications, resolvePlayerStructuredConsumerPolicy, sanitizeTerminalText } from "../src/playerStructuredConsumer.mjs";
import { appendBrowserPublicationNode, consumeLiveActionDisplay, deliverLivePlayerEntries, deliverPlayerPublication, dispatchPlayerActionWithConsumerMode, ensurePlayerPublicationConsumerMode, reconcileBrowserPublicationNodes, retryPlayerPublicationAcknowledgement, retryPreCutoverPlayerPublicationEvidence, sinkReceiptIdentity, writeCliPublication } from "../src/playerDisplaySink.mjs";
import { PlayerPublicationDeliveryController } from "../src/playerPublicationDelivery.mjs";
import { getRuntimeConfig, parseConfig } from "../src/config.mjs";

function ids() { let value = 0; return () => String(++value); }
function interpreter() { return { async interpretPlayerInput(request) { return { schemaVersion: 1, requestId: request.requestId, correlationId: request.correlationId, serverCorrelationId: "server-1", result: { schemaVersion: 1, requestId: request.requestId, correlationId: request.correlationId, modelOutput: { schemaVersion: 1, alternatives: [{ alternativeId: "alternative-1", confidence: 1, speechActs: [{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }] }] }, diagnostics: { providerName: "test", model: "test", attemptCount: 1, elapsedMs: 0 } } }; } }; }
function game(options = {}) { return WerewolfGame.create({ seed: 1, scenario: "sample", shuffleRoles: false, createId: ids(), interpreterValidationEnabled: true, playerConversationCommitEnabled: true, playerStructuredConsumerEnabled: true, interpreterProvider: interpreter(), responseProvider: { async generateResponse() { return { text: "response", providerName: "test", model: "test", usage: null, notes: [] }; } }, ...options }); }
async function action(instance = game()) { return { instance, result: await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }) }; }
function authoritative(instance) { return structuredClone({ stateVersion: instance.state.stateVersion, turnId: instance.state.turnId, turnOrder: instance.state.turnOrder, phase: instance.state.phase, conversation: instance.state.conversation, playerLog: instance.state.playerLog, players: instance.state.players }); }
function transitionIdentity(result) { return { modeTransitionId: result.modeTransitionId, gameSessionId: result.gameSessionId, consumerId: result.consumerId, sinkType: result.sinkType, proposedCutoverPublicationSlotOrder: result.proposedCutoverPublicationSlotOrder }; }
function fakeDom({ appendThrows = false, attach = true } = {}) { const document = { createElement() { return { className: "", dataset: {}, textContent: "", children: [], parentNode: null, append(...children) { this.children.push(...children); }, remove() { if (!this.parentNode) return; this.parentNode.children = this.parentNode.children.filter((node) => node !== this); this.parentNode = null; } }; } }; const container = { children: [], append(node) { if (appendThrows) throw new Error("append failed"); if (attach) { this.children.push(node); node.parentNode = this; } }, replaceChildren(...nodes) { for (const child of this.children) if (!nodes.includes(child)) child.parentNode = null; this.children = [...nodes]; for (const node of nodes) node.parentNode = this; }, querySelectorAll() { return this.children.filter((node) => node.dataset?.publicationId); } }; return { document, container }; }
async function consume(instance, result, sinkType = "cli", options = {}) { const visible = options.visible ?? [], bookkeeping = options.bookkeeping ?? new Map(), write = options.write ?? (async (entry) => { visible.push(entry); return entry; }); await consumeLiveActionDisplay({ game: instance, action: result, consumerId: `${sinkType}-main`, sinkType, bookkeeping, writeStructured: write, writeLegacy: write }); return { visible, bookkeeping }; }

test("delivery state machine requires sink success receipt and never mutates authoritative state", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], before = authoritative(instance), attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "prepared"); assert.deepEqual(authoritative(instance), before);
  assert.throws(() => instance.getPlayerPublicationSinkReceipt({ publicationId }), (error) => error.code === "invalid_sink_success_receipt"); const capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "in_flight"); assert.throws(() => instance.acknowledgePlayerPublication({}), (error) => error.code === "invalid_sink_success_receipt");
  const receipt = instance.completePlayerPublicationSink(capability); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "sink_succeeded"); const acknowledged = instance.acknowledgePlayerPublication(receipt); assert.equal(acknowledged.status, "acknowledged"); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "acknowledged"); assert.deepEqual(authoritative(instance), before);
});

test("publication resolution failure becomes terminal for the session", () => {
  let id = 0; const controller = new PlayerPublicationDeliveryController({ gameSessionId: "game-1", createId: () => String(++id), enabled: true, listPublications: () => [{ publicationId: "publication-1", publicationSlotOrder: 0 }], resolvePublication() { const error = new Error("compatibility_mapping_conflict"); error.code = "compatibility_mapping_conflict"; throw error; } }); assert.throws(() => controller.prepare({ publicationId: "publication-1", consumerId: "browser", sinkType: "browser" }), (error) => error.code === "compatibility_mapping_conflict"); assert.equal(controller.stateFor("publication-1"), "failed_terminal"); assert.throws(() => controller.prepare({ publicationId: "publication-1", consumerId: "browser", sinkType: "browser" }), (error) => error.code === "compatibility_mapping_conflict");
});

test("sink failure is retryable and successful retry reuses the authoritative publication", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], before = authoritative(instance), first = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "cli", sinkType: "cli" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: first.deliveryAttemptId }); instance.failPlayerPublicationSink(capability); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "failed_retryable"); assert.equal(instance.getPlayerPublicationDeliveryCandidates().includes(publicationId), true);
  let writes = 0; await deliverPlayerPublication({ game: instance, publicationId, consumerId: "cli", sinkType: "cli", write: async () => { writes += 1; } }); assert.equal(writes, 1); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "acknowledged"); assert.deepEqual(authoritative(instance), before);
});

test("duplicate acknowledgement is idempotent and emits exactly one observer event per invocation", async () => {
  const events = [], instance = game({ playerStructuredConsumerObserver: (entry) => events.push(entry) }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = instance.completePlayerPublicationSink(capability), first = instance.acknowledgePlayerPublication(receipt), second = instance.acknowledgePlayerPublication(receipt); assert.equal(first, second); assert.equal(events.filter((entry) => entry.outcomeCategory === "publication_acknowledged").length, 1); assert.equal(events.filter((entry) => entry.outcomeCategory === "duplicate_ack_suppressed").length, 1);
});

test("observer failure preserves acknowledgement and ack-only retry never rewrites the sink", async () => {
  const instance = game({ playerStructuredConsumerObserver() { throw new Error("observer"); } }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0]; let writes = 0, identity; await deliverPlayerPublication({ game: instance, publicationId, consumerId: "browser", sinkType: "browser", write: async () => { writes += 1; }, onSinkSucceeded: (value) => { identity = value; } }); const duplicate = retryPlayerPublicationAcknowledgement({ game: instance, deliveryIdentity: identity }); assert.equal(duplicate.status, "acknowledged"); assert.equal(writes, 1);
});

test("sink success followed by acknowledgement failure retries acknowledgement only", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], acknowledge = instance.acknowledgePlayerPublication.bind(instance); let firstAck = true, writes = 0; instance.acknowledgePlayerPublication = (receipt) => { if (firstAck) { firstAck = false; const error = new Error("ack transport"); throw error; } return acknowledge(receipt); };
  let identity; await assert.rejects(deliverPlayerPublication({ game: instance, publicationId, consumerId: "browser", sinkType: "browser", write: async () => { writes += 1; }, onSinkSucceeded: (value) => { identity = value; } }), (error) => error.acknowledgementOnlyRetry === true); const resultAck = retryPlayerPublicationAcknowledgement({ game: instance, deliveryIdentity: identity }); assert.equal(resultAck.status, "acknowledged"); assert.equal(writes, 1);
});

test("wrong receipt, reset receipt, generation switch, and concurrent attempts fail closed", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }); assert.throws(() => instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser" }), (error) => error.code === "publication_not_prepared"); assert.throws(() => instance.requestPlayerPublicationConsumerMode({ consumerId: "browser", sinkType: "browser", requestedMode: "legacy" }), (error) => error.code === "consumer_mode_switch_in_flight"); const receipt = instance.completePlayerPublicationSink(capability); instance.destroy(); assert.throws(() => instance.acknowledgePlayerPublication(receipt), (error) => error.code === "stale_publication_session");
});

test("prepared attempt becomes stale after a quiescent consumer generation switch", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "cli", sinkType: "cli" }); instance.requestPlayerPublicationConsumerMode({ consumerId: "cli", sinkType: "cli", requestedMode: "legacy" }); assert.throws(() => instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), (error) => error.code === "stale_consumer_generation");
});

test("ON to OFF rollback never redisplays an acknowledged legacy player entry", async () => {
  const { instance, result } = await action(); await deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} }); instance.playerStructuredConsumerEnabled = false; const rollback = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(rollback.playerFacingEntries.filter((entry) => entry.structured).length, 1); assert.deepEqual(rollback.livePlayerDisplayEntries, []); assert.equal(instance.state.conversation.publications.length, 1);
});

test("get_state, history projection, diagnostics, and replay do not start delivery", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0]; assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen"); await instance.dispatchPlayerAction({ type: "get_state" }); instance.getDeveloperDiagnostics(); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen"); const record = instance.state.conversation.idempotencyRecords[0]; await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint }); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen");
});

test("browser-like DOM and CLI sinks write exactly once, fail without ack, and sanitize output", async () => {
  const { document: fakeDocument, container } = fakeDom();
  const browser = await action(), browserEntry = browser.result.playerFacingEntries.find((entry) => entry.structured); await deliverLivePlayerEntries({ game: browser.instance, entries: browser.result.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery"), consumerId: "browser", sinkType: "browser", writeStructured: async (entry) => appendBrowserPublicationNode({ document: fakeDocument, container, entry }), writeLegacy: async () => {} }); assert.equal(container.children.length, 1); assert.equal(container.children[0].dataset.publicationId, browserEntry.publicationId); assert.equal(container.children[0].children[1].textContent, "hello");
  const cli = await action(), cliEntry = cli.result.playerFacingEntries.find((entry) => entry.structured), output = []; await deliverLivePlayerEntries({ game: cli.instance, entries: cli.result.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery"), consumerId: "cli", sinkType: "cli", writeStructured: async (entry) => writeCliPublication({ entry, write: async (text) => output.push(text) }), writeLegacy: async () => {} }); assert.equal(output.length, 1); assert.equal(output[0].endsWith("hello"), true); const sanitized = []; await writeCliPublication({ entry: { ...cliEntry, message: "a\u001bb" }, write: async (text) => sanitized.push(text) }); assert.equal(sanitized[0].endsWith("a[control]b"), true);
  const failed = await action(); await assert.rejects(deliverPlayerPublication({ game: failed.instance, publicationId: failed.result.deliveryPublicationIds[0], consumerId: "browser", sinkType: "browser", write: async () => { throw new Error("append failed"); } }), /append failed/); assert.notEqual(failed.instance.playerPublicationDeliveryController.stateFor(failed.result.deliveryPublicationIds[0]), "acknowledged");
});

test("history results and replay never become live delivery envelopes", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], record = instance.state.conversation.idempotencyRecords[0];
  const replayUnacknowledged = await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint, logCursor: 0 }); assert.equal(replayUnacknowledged.playerFacingEntries.some((entry) => entry.publicationId === publicationId), true); assert.deepEqual(replayUnacknowledged.livePlayerDisplayEntries, []); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "unseen");
  await deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} });
  const replayAcknowledged = await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint, logCursor: 0 }), state = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(replayAcknowledged.playerFacingEntries.filter((entry) => entry.publicationId === publicationId).length, 1); assert.deepEqual(replayAcknowledged.livePlayerDisplayEntries, []); assert.deepEqual(state.livePlayerDisplayEntries, []);
  const historyAgain = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.deepEqual(historyAgain.playerFacingEntries, state.playerFacingEntries); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "acknowledged");
});

test("normal stale cursor suppresses acknowledged delivery while preserving mixed history order", async () => {
  const { instance, result } = await action(); await deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} }); instance.state.phase = "day_discussion";
  const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), oldPublication = result.deliveryPublicationIds[0]; assert.equal(next.playerFacingEntries.filter((entry) => entry.publicationId === oldPublication).length, 1); assert.equal(next.livePlayerDisplayEntries.some((entry) => entry.publicationId === oldPublication), false); assert.deepEqual(next.livePlayerDisplayEntries.slice(-2).map((entry) => entry.kind), ["player_publication_delivery", "legacy_display"]);
});

test("sink writes only the frozen controller-prepared payload", async () => {
  const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], seen = [];
  await deliverPlayerPublication({ game: instance, publicationId, consumerId: "browser", sinkType: "browser", displayEntry: { publicationId: "other", day: 99, phase: "night", message: "forged" }, write: async (entry) => { seen.push(entry); assert.equal(Object.isFrozen(entry), true); } });
  assert.equal(seen[0].publicationId, publicationId); assert.equal(seen[0].message, "hello"); assert.notEqual(seen[0].day, 99); assert.notEqual(seen[0].phase, "night");
});

test("sink receipt lookup requires the complete exact delivery identity", async () => {
  const events = [], instance = game({ playerStructuredConsumerObserver: (event) => events.push(event) }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser-exact", sinkType: "browser" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = instance.completePlayerPublicationSink(capability), identity = sinkReceiptIdentity(receipt);
  assert.equal(instance.getPlayerPublicationSinkReceipt(identity), receipt);
  for (const [field, value, code] of [["consumerId", "wrong", "publication_not_delivered"], ["consumerGeneration", identity.consumerGeneration + 1, "stale_consumer_generation"], ["deliveryAttemptId", "wrong", "publication_not_delivered"], ["sinkType", "cli", "publication_not_delivered"], ["deliveryMode", "legacy", "publication_not_delivered"], ["gameSessionId", "wrong", "stale_publication_session"], ["receiptId", "wrong", "publication_not_delivered"]]) assert.throws(() => instance.getPlayerPublicationSinkReceipt({ ...identity, [field]: value }), (error) => error.code === code);
  assert.throws(() => instance.getPlayerPublicationSinkReceipt({ publicationId }), (error) => error.code === "invalid_sink_success_receipt"); assert.throws(() => instance.acknowledgePlayerPublication(structuredClone(receipt)), (error) => error.code === "invalid_sink_success_receipt"); assert.deepEqual(events.filter((event) => event.outcomeCategory === "stale_ack_rejected").map((event) => event.reasonCode), ["stale_consumer_generation", "stale_publication_session"]);
});

test("cutover blocks live backfill without truncating structured history", async () => {
  const instance = game({ playerStructuredConsumerEnabled: false }), old = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), oldPublication = instance.state.conversation.publications[0].publicationId; assert.equal(old.livePlayerDisplayEntries.some((entry) => entry.publicationId === oldPublication && entry.deliveryMode === "legacy_pre_cutover"), true); await consumeLiveActionDisplay({ game: instance, action: old, consumerId: "browser-main", sinkType: "browser", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => {} });
  instance.state.phase = "day_discussion"; const transition = instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "structured" }); assert.equal(transition.status, "completed"); const cutoverRead = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(cutoverRead.playerFacingEntries.filter((entry) => entry.publicationId === oldPublication).length, 1); assert.deepEqual(cutoverRead.livePlayerDisplayEntries, []);
  const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), newPublication = instance.state.conversation.publications.at(-1).publicationId; assert.equal(next.livePlayerDisplayEntries.some((entry) => entry.publicationId === oldPublication), false); assert.equal(next.livePlayerDisplayEntries.some((entry) => entry.publicationId === newPublication), true);
});

test("combined browser and CLI action paths use only the live envelope and exact bookkeeping", async () => {
  const { document: fakeDocument, container } = fakeDom(), browser = await action(), browserBookkeeping = new Map(), browserHistory = [];
  await consumeLiveActionDisplay({ game: browser.instance, action: browser.result, consumerId: "browser-main", sinkType: "browser", bookkeeping: browserBookkeeping, writeStructured: async (entry) => { browserHistory.push(entry); return appendBrowserPublicationNode({ document: fakeDocument, container, entry }); }, writeLegacy: async (entry) => browserHistory.push(entry) }); assert.equal(container.children.length, 1); assert.equal(browserHistory.length, 2); const browserIdentity = [...browserBookkeeping.values()][0].identity; assert.equal(browserIdentity.receiptId, container.children[0].dataset.receiptId); browser.instance.destroy(); assert.throws(() => retryPlayerPublicationAcknowledgement({ game: browser.instance, deliveryIdentity: browserIdentity }), (error) => error.code === "stale_publication_session");
  const cli = await action(), cliBookkeeping = new Map(), output = [], cliHistory = []; await consumeLiveActionDisplay({ game: cli.instance, action: cli.result, consumerId: "cli-main", sinkType: "cli", bookkeeping: cliBookkeeping, writeStructured: async (entry) => { cliHistory.push(entry); return writeCliPublication({ entry, write: async (text) => output.push(text) }); }, writeLegacy: async (entry) => cliHistory.push(entry) }); assert.equal(output.length, 1); assert.equal(cliHistory.length, 2); assert.equal([...cliBookkeeping.values()][0].identity.consumerId, "cli-main"); const historyOnly = await cli.instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); await consumeLiveActionDisplay({ game: cli.instance, action: historyOnly, consumerId: "cli-main", sinkType: "cli", bookkeeping: cliBookkeeping, writeStructured: async () => { throw new Error("history reached sink"); }, writeLegacy: async () => { throw new Error("history reached sink"); } }); assert.equal(output.length, 1); assert.equal(cliHistory.length, 2);
});

test("failed sink remains pending across replay and cursor advance", async () => {
  const { instance, result } = await action(), oldPublication = result.deliveryPublicationIds[0], record = instance.state.conversation.idempotencyRecords[0]; await assert.rejects(deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "browser", sinkType: "browser", writeStructured: async () => { throw new Error("sink failed"); }, writeLegacy: async () => {} }), /sink failed/);
  const replay = await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint, logCursor: instance.state.playerLog.length }); assert.deepEqual(replay.livePlayerDisplayEntries, []); instance.state.phase = "day_discussion";
  const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), playerEnvelopes = next.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery"); assert.equal(playerEnvelopes[0].publicationId, oldPublication); assert.equal(playerEnvelopes.length, 2); assert.equal(next.livePlayerDisplayEntries.at(-1).kind, "legacy_display");
});

test("ack-only pending survives cursor advance and retries without another sink write", async () => {
  const { instance, result } = await action(), bookkeeping = new Map(), acknowledge = instance.acknowledgePlayerPublication.bind(instance); let failures = 2, writes = 0; instance.acknowledgePlayerPublication = (receipt) => { if (failures-- > 0) throw new Error("ack unavailable"); return acknowledge(receipt); };
  await assert.rejects(consumeLiveActionDisplay({ game: instance, action: result, consumerId: "browser-main", sinkType: "browser", bookkeeping, writeStructured: async () => { writes += 1; }, writeLegacy: async () => {} }), /ack unavailable/); assert.equal(writes, 1); const state = await instance.dispatchPlayerAction({ type: "get_state", logCursor: instance.state.playerLog.length }); assert.deepEqual(state.livePlayerDisplayEntries, []); instance.state.phase = "day_discussion";
  const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }); assert.equal(next.livePlayerDisplayEntries[0].acknowledgementOnly, true); await consumeLiveActionDisplay({ game: instance, action: next, consumerId: "browser-main", sinkType: "browser", bookkeeping, writeStructured: async () => { writes += 1; }, writeLegacy: async () => {} }); assert.equal(writes, 2); assert.equal(instance.playerPublicationDeliveryController.stateFor(result.deliveryPublicationIds[0]), "acknowledged");
});

test("ON to OFF delivers unseen, retryable, and new publications through legacy acknowledgement", async () => {
  const instance = game(), first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }), oldPublication = first.deliveryPublicationIds[0]; await assert.rejects(deliverLivePlayerEntries({ game: instance, entries: first.livePlayerDisplayEntries, consumerId: "cli-main", sinkType: "cli", writeStructured: async () => { throw new Error("structured sink failed"); }, writeLegacy: async () => {} }), /structured sink failed/); instance.requestPlayerPublicationConsumerMode({ consumerId: "cli-main", sinkType: "cli", requestedMode: "legacy" }); instance.state.phase = "day_discussion";
  const rollback = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), legacyPlayers = rollback.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery"); assert.equal(legacyPlayers.length, 2); assert.equal(legacyPlayers.every((entry) => entry.deliveryMode === "legacy"), true); assert.equal(legacyPlayers[0].publicationId, oldPublication);
  const visible = [], before = authoritative(instance); await consumeLiveActionDisplay({ game: instance, action: rollback, consumerId: "cli-main", sinkType: "cli", bookkeeping: new Map(), writeStructured: async () => { throw new Error("structured writer used"); }, writeLegacy: async (entry) => visible.push(entry) }); assert.equal(visible.filter((entry) => entry.phase === "player_question").length, 2); assert.equal(instance.playerPublicationDeliveryController.stateFor(oldPublication), "acknowledged"); assert.equal(rollback.playerFacingEntries.filter((entry) => entry.structured).length, 1); assert.deepEqual(authoritative(instance), before);
  const unseen = game(), unseenFirst = await unseen.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }), unseenPublication = unseenFirst.deliveryPublicationIds[0]; unseen.requestPlayerPublicationConsumerMode({ consumerId: "cli-main", sinkType: "cli", requestedMode: "legacy" }); unseen.state.phase = "day_discussion"; const unseenRollback = await unseen.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: unseen.state.playerLog.length }); assert.equal(unseenRollback.livePlayerDisplayEntries.some((entry) => entry.publicationId === unseenPublication && entry.deliveryMode === "legacy"), true);
});

test("stale acknowledgement observer uses one redacted outcome per invocation", async () => {
  const events = [], instance = game({ playerStructuredConsumerObserver: (event) => events.push(event) }), { result } = await action(instance), publicationId = result.deliveryPublicationIds[0], attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser", sinkType: "browser", deliveryMode: "structured" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = instance.completePlayerPublicationSink(capability); instance.destroy(); assert.throws(() => instance.acknowledgePlayerPublication(receipt), (error) => error.code === "stale_publication_session"); assert.deepEqual(events.filter((event) => event.outcomeCategory === "stale_ack_rejected").map((event) => event.reasonCode), ["stale_publication_session"]);
  const isolated = game({ playerStructuredConsumerObserver() { throw new Error("observer"); } }), isolatedAction = await action(isolated), isolatedAttempt = isolated.preparePlayerPublicationDelivery({ publicationId: isolatedAction.result.deliveryPublicationIds[0], consumerId: "cli", sinkType: "cli", deliveryMode: "structured" }), isolatedCapability = isolated.beginPlayerPublicationSink({ deliveryAttemptId: isolatedAttempt.deliveryAttemptId }), isolatedReceipt = isolated.completePlayerPublicationSink(isolatedCapability); isolated.destroy(); assert.throws(() => isolated.acknowledgePlayerPublication(isolatedReceipt), (error) => error.code === "stale_publication_session");
});

test("rejected in-flight mode switch is atomic and retries after acknowledgement", async () => {
  for (const sinkType of ["browser", "cli"]) { const { instance, result } = await action(), publicationId = result.deliveryPublicationIds[0], consumerId = `${sinkType}-main`, attempt = instance.preparePlayerPublicationDelivery({ publicationId, consumerId, sinkType, deliveryMode: "structured" }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), before = instance.getPlayerPublicationConsumerModeState();
    assert.throws(() => instance.requestPlayerPublicationConsumerMode({ consumerId, sinkType, requestedMode: "legacy" }), (error) => error.code === "consumer_mode_switch_in_flight"); assert.deepEqual(instance.getPlayerPublicationConsumerModeState(), before); const receipt = instance.completePlayerPublicationSink(capability); instance.acknowledgePlayerPublication(receipt); instance.requestPlayerPublicationConsumerMode({ consumerId, sinkType, requestedMode: "legacy" }); instance.state.phase = "day_discussion";
    const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }); assert.equal(instance.getPlayerPublicationConsumerModeState().effectiveMode, "legacy"); assert.equal(next.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery").every((entry) => entry.deliveryMode === "legacy"), true); const visible = []; await consumeLiveActionDisplay({ game: instance, action: next, consumerId, sinkType, bookkeeping: new Map(), writeStructured: async () => { throw new Error("wrong mode"); }, writeLegacy: async (entry) => visible.push(entry) }); assert.equal(visible.filter((entry) => entry.phase === "player_question").length, 1); }
});

test("pre-cutover legacy-delivered publications never redisplay after rollback", async () => {
  for (const sinkType of ["browser", "cli"]) { const instance = game({ playerStructuredConsumerEnabled: false }), old = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), oldPublication = instance.state.conversation.publications[0].publicationId, initialVisible = []; await consumeLiveActionDisplay({ game: instance, action: old, consumerId: `${sinkType}-main`, sinkType, bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async (entry) => initialVisible.push(entry) }); assert.equal(initialVisible.filter((entry) => entry.phase === "player_question").length, 1); assert.equal(instance.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds().has(oldPublication), true);
    instance.requestPlayerPublicationConsumerMode({ consumerId: `${sinkType}-main`, sinkType, requestedMode: "structured" }); await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); instance.requestPlayerPublicationConsumerMode({ consumerId: `${sinkType}-main`, sinkType, requestedMode: "legacy" }); instance.state.phase = "day_discussion"; const rollback = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }); assert.equal(rollback.livePlayerDisplayEntries.some((entry) => entry.publicationId === oldPublication), false); assert.equal(rollback.playerFacingEntries.filter((entry) => entry.publicationId === oldPublication).length, 1); assert.equal(rollback.livePlayerDisplayEntries.filter((entry) => entry.kind === "legacy_display").every((entry) => entry.entry.phase !== "player_question" || entry.entry.message !== old.playerFacingEntries.find((entry) => entry.phase === "player_question")?.message), true); }
  const failed = game({ playerStructuredConsumerEnabled: false }), failedAction = await failed.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), failedPublication = failed.state.conversation.publications[0].publicationId; await assert.rejects(consumeLiveActionDisplay({ game: failed, action: failedAction, consumerId: "browser-main", sinkType: "browser", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async (entry) => { if (entry.phase === "player_question") throw new Error("legacy sink failed"); } }), /legacy sink failed/); assert.equal(failed.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds().has(failedPublication), false);
});

test("first cutover watermark survives repeated cycles and partial acknowledgement", async () => {
  const instance = game(), first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }), firstPublication = first.deliveryPublicationIds[0], watermark = instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder; await assert.rejects(deliverLivePlayerEntries({ game: instance, entries: first.livePlayerDisplayEntries, consumerId: "browser-main", sinkType: "browser", writeStructured: async () => { throw new Error("sink failed"); }, writeLegacy: async () => {} }), /sink failed/);
  instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "legacy" }); instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "structured" }); assert.equal(instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder, watermark); instance.state.phase = "day_discussion"; const second = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), secondPublication = instance.state.conversation.publications.at(-1).publicationId; assert.equal(second.deliveryPublicationIds.includes(firstPublication), true); await consumeLiveActionDisplay({ game: instance, action: { ...second, livePlayerDisplayEntries: second.livePlayerDisplayEntries.filter((entry) => entry.publicationId === firstPublication) }, consumerId: "browser-main", sinkType: "browser", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => {} });
  instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "legacy" }); instance.state.phase = "day_discussion"; const duringOff = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }), offPublication = instance.state.conversation.publications.at(-1).publicationId; instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "structured" }); instance.state.phase = "day_discussion"; const final = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }); assert.equal(instance.playerPublicationDeliveryController.cutoverPublicationSlotOrder, watermark); assert.equal(final.deliveryPublicationIds.includes(firstPublication), false); assert.equal(final.deliveryPublicationIds.includes(secondPublication), true); assert.equal(final.deliveryPublicationIds.includes(offPublication), true); assert.equal(duringOff.deliveryPublicationIds.includes(offPublication), true);
});

test("new controller observes valid old-session identity and receipt exactly once", () => {
  let id = 0; const publication = { publicationId: "publication-old", publicationSlotOrder: 0 }, old = new PlayerPublicationDeliveryController({ gameSessionId: "session-old", createId: () => String(++id), enabled: true, listPublications: () => [publication], resolvePublication: () => Object.freeze({ message: "safe" }) }), attempt = old.prepare({ publicationId: publication.publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "structured" }), capability = old.begin({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = old.complete(capability), identity = sinkReceiptIdentity(receipt), events = [], next = new PlayerPublicationDeliveryController({ gameSessionId: "session-new", createId: () => String(++id), observer: (event) => events.push(event), enabled: true, listPublications: () => [], resolvePublication: () => null });
  assert.throws(() => next.receiptFor(identity), (error) => error.code === "stale_publication_session"); assert.deepEqual(events.map((event) => [event.outcomeCategory, event.reasonCode]), [["stale_ack_rejected", "stale_publication_session"]]); assert.throws(() => next.acknowledge(receipt), (error) => error.code === "stale_publication_session"); assert.equal(events.filter((event) => event.outcomeCategory === "stale_ack_rejected").length, 2); const forged = Object.freeze({ ...receipt, gameSessionId: "session-new", receiptId: "forged-current" }); assert.throws(() => next.acknowledge(forged), (error) => error.code === "invalid_sink_success_receipt"); assert.equal(events.length, 2);
  const isolated = new PlayerPublicationDeliveryController({ gameSessionId: "session-new", createId: () => String(++id), observer() { throw new Error("observer"); }, enabled: true, listPublications: () => [], resolvePublication: () => null }); assert.throws(() => isolated.receiptFor(identity), (error) => error.code === "stale_publication_session");
});

test("terminal resolution failure persists across modes and clears only with a new session", async () => {
  const structured = await action(), publicationId = structured.result.deliveryPublicationIds[0], originalResolve = structured.instance.playerPublicationDeliveryController.resolvePublication; structured.instance.playerPublicationDeliveryController.resolvePublication = () => { const error = new Error("structured terminal"); error.code = "structured_terminal_failure"; throw error; }; assert.throws(() => structured.instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "structured" }), (error) => error.code === "structured_terminal_failure"); structured.instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "legacy" }); assert.equal(structured.instance.getPlayerPublicationDeliveryCandidates().includes(publicationId), false); assert.throws(() => structured.instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "legacy" }), (error) => error.code === "structured_terminal_failure"); structured.instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "structured" }); assert.equal(structured.instance.getPlayerPublicationDeliveryCandidates().includes(publicationId), false); assert.throws(() => structured.instance.preparePlayerPublicationDelivery({ publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "structured" }), (error) => error.code === "structured_terminal_failure");
  const legacy = await action(); legacy.instance.requestPlayerPublicationConsumerMode({ consumerId: "cli-main", sinkType: "cli", requestedMode: "legacy" }); const legacyPublication = legacy.result.deliveryPublicationIds[0]; legacy.instance.playerPublicationDeliveryController.resolvePublication = () => { const error = new Error("legacy terminal"); error.code = "legacy_terminal_failure"; throw error; }; assert.throws(() => legacy.instance.preparePlayerPublicationDelivery({ publicationId: legacyPublication, consumerId: "cli-main", sinkType: "cli", deliveryMode: "legacy" }), (error) => error.code === "legacy_terminal_failure"); legacy.instance.requestPlayerPublicationConsumerMode({ consumerId: "cli-main", sinkType: "cli", requestedMode: "structured" }); assert.equal(legacy.instance.getPlayerPublicationDeliveryCandidates().includes(legacyPublication), false); assert.throws(() => legacy.instance.preparePlayerPublicationDelivery({ publicationId: legacyPublication, consumerId: "cli-main", sinkType: "cli", deliveryMode: "structured" }), (error) => error.code === "legacy_terminal_failure");
  const reset = await action(); reset.instance.playerPublicationDeliveryController.resolvePublication = originalResolve; assert.equal(reset.instance.playerPublicationDeliveryController.stateFor(reset.result.deliveryPublicationIds[0]), "unseen");
});

test("first cutover rejects undelivered legacy publications until cursor-independent retry succeeds", async () => {
  for (const sinkType of ["browser", "cli"]) { const instance = game({ playerStructuredConsumerEnabled: false }), consumerId = `${sinkType}-main`, first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), firstPublication = instance.state.conversation.publications[0].publicationId; await assert.rejects(consumeLiveActionDisplay({ game: instance, action: first, consumerId, sinkType, bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => { throw new Error("legacy sink failed"); } }), /legacy sink failed/); const before = authoritative(instance), pending = instance.requestPlayerPublicationConsumerMode({ consumerId, sinkType, requestedMode: "structured" }); assert.equal(pending.reasonCode, "pre_cutover_delivery_pending"); assert.equal(pending.effectiveMode, "legacy"); await assert.rejects(instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }), (error) => error.code === "consumer_mode_transition_pending"); assert.deepEqual(authoritative(instance), before);
    const candidates = instance.getPendingPreCutoverPlayerPublications({ ...transitionIdentity(pending), limit: 1 }); assert.equal(candidates.length, 1); assert.equal(candidates[0].publicationId, firstPublication); assert.equal(candidates[0].deliveryMode, "legacy_pre_cutover"); await consumeLiveActionDisplay({ game: instance, action: { livePlayerDisplayEntries: candidates.map((candidate) => ({ kind: "player_publication_delivery", ...candidate })) }, consumerId, sinkType, bookkeeping: new Map(), writeStructured: async () => { throw new Error("structured backfill"); }, writeLegacy: async () => {} }); const completed = instance.completePlayerPublicationConsumerModeTransition(transitionIdentity(pending)); assert.equal(completed.status, "completed"); assert.equal(completed.consumerGeneration, pending.consumerGeneration + 1); assert.deepEqual(authoritative(instance), before); const history = await instance.dispatchPlayerAction({ type: "get_state", logCursor: 0 }); assert.equal(history.playerFacingEntries.filter((entry) => entry.publicationId === firstPublication).length, 1); assert.deepEqual(history.livePlayerDisplayEntries, []); }
});

test("explicit mode state freezes transition identity and applies generation exactly once", () => {
  let nextId = 0;
  const empty = new PlayerPublicationDeliveryController({ gameSessionId: "session-empty", createId: () => String(++nextId), enabled: false, listPublications: () => [], resolvePublication: () => null });
  const immediate = empty.requestMode({ gameSessionId: "session-empty", consumerId: "browser-main", sinkType: "browser", requestedMode: "structured", nextPublicationSlotOrder: 0 });
  assert.equal(immediate.status, "completed"); assert.equal(immediate.consumerGeneration, 1); assert.equal(empty.modeState().committedCutoverPublicationSlotOrder, 0);
  assert.equal(empty.requestMode({ gameSessionId: "session-empty", consumerId: "browser-main", sinkType: "browser", requestedMode: "structured", nextPublicationSlotOrder: 0 }).consumerGeneration, 1);

  const publications = [{ publicationId: "publication-1", publicationSlotOrder: 0 }];
  const controller = new PlayerPublicationDeliveryController({ gameSessionId: "session-1", createId: () => String(++nextId), enabled: false, listPublications: () => publications, resolvePublication: () => Object.freeze({ day: 1, phase: "player_question", message: "safe" }), resolvePreCutoverIdentity: () => ({ compatibilityMappingId: "mapping-1", legacyEntryId: "legacy-1", legacyLogAppendOrder: 3, legacyEntryFingerprint: "fingerprint-1" }) });
  const pending = controller.requestMode({ gameSessionId: "session-1", consumerId: "cli-main", sinkType: "cli", requestedMode: "structured", nextPublicationSlotOrder: 1 }), duplicate = controller.requestMode({ gameSessionId: "session-1", consumerId: "cli-main", sinkType: "cli", requestedMode: "structured", nextPublicationSlotOrder: 99 });
  assert.equal(pending.reasonCode, "pre_cutover_delivery_pending"); assert.equal(pending.modeTransitionId, duplicate.modeTransitionId); assert.equal(duplicate.proposedCutoverPublicationSlotOrder, 1); assert.deepEqual([controller.modeState().requestedMode, controller.modeState().effectiveMode, controller.modeState().consumerGeneration], ["structured", "legacy", 0]);
  assert.throws(() => controller.pendingPreCutover({ ...transitionIdentity(pending), consumerId: "other", limit: 1 }), (error) => error.code === "consumer_mode_transition_conflict");
  const attempt = controller.prepare({ publicationId: "publication-1", consumerId: "cli-main", sinkType: "cli", deliveryMode: "legacy_pre_cutover", modeTransitionId: pending.modeTransitionId }), capability = controller.begin({ deliveryAttemptId: attempt.deliveryAttemptId });
  assert.throws(() => controller.cancelTransition(transitionIdentity(pending)), (error) => error.code === "consumer_mode_switch_in_flight"); controller.fail(capability);
  const cancelled = controller.cancelTransition(transitionIdentity(pending)); assert.equal(cancelled.status, "cancelled"); assert.equal(controller.cancelTransition(transitionIdentity(pending)), cancelled); assert.equal(controller.consumerGeneration, 0);
  const next = controller.requestMode({ gameSessionId: "session-1", consumerId: "cli-main", sinkType: "cli", requestedMode: "structured", nextPublicationSlotOrder: 1 }); assert.notEqual(next.modeTransitionId, pending.modeTransitionId);
});

test("adapter drains before dispatch and submits the held authoritative command exactly once", async () => {
  let interpreterCalls = 0, npcCalls = 0;
  const countedInterpreter = { async interpretPlayerInput(request) { interpreterCalls += 1; return interpreter().interpretPlayerInput(request); } }, countedNpc = { async generateResponse() { npcCalls += 1; return { text: "response", providerName: "test", model: "test", usage: null, notes: [] }; } };
  const instance = game({ playerStructuredConsumerEnabled: false, interpreterProvider: countedInterpreter, responseProvider: countedNpc }), first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), firstPlayer = first.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery");
  await assert.rejects(consumeLiveActionDisplay({ game: instance, action: { ...first, livePlayerDisplayEntries: firstPlayer }, consumerId: "browser-main", sinkType: "browser", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => { throw new Error("DOM unavailable"); } }), /DOM unavailable/);
  const before = authoritative(instance), bookkeeping = new Map(); let drainWrites = 0;
  const second = await dispatchPlayerActionWithConsumerMode({ game: instance, action: { type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length }, requestedMode: "structured", consumerId: "browser-main", sinkType: "browser", bookkeeping, writeStructured: async () => { throw new Error("no backfill"); }, writeLegacy: async () => { drainWrites += 1; assert.equal(interpreterCalls, 1); assert.equal(npcCalls, 1); } });
  assert.equal(drainWrites, 1); assert.equal(interpreterCalls, 2); assert.equal(npcCalls, 2); assert.equal(instance.state.turnOrder, before.turnOrder + 1); assert.equal(instance.state.stateVersion, before.stateVersion + 1); assert.equal(second.actionType, "ask_npc"); assert.equal(instance.getPlayerPublicationConsumerModeState().effectiveMode, "structured");
});

test("pre-cutover drain is bounded, cursor-independent, partial, and exact", async () => {
  const instance = game({ playerStructuredConsumerEnabled: false });
  await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }); instance.state.phase = "day_discussion";
  await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: instance.state.playerLog.length });
  const pending = instance.requestPlayerPublicationConsumerMode({ consumerId: "cli-main", sinkType: "cli", requestedMode: "structured" }), identity = transitionIdentity(pending), first = instance.getPendingPreCutoverPlayerPublications({ ...identity, limit: 1 }), duplicate = instance.getPendingPreCutoverPlayerPublications({ ...identity, limit: 1 });
  assert.equal(pending.pendingCount, 2); assert.deepEqual(first, duplicate); assert.equal(first.length, 1); assert.equal(first[0].legacyLogAppendOrder < instance.state.playerLog.length, true);
  await consumeLiveActionDisplay({ game: instance, action: { livePlayerDisplayEntries: [{ kind: "player_publication_delivery", ...first[0] }] }, consumerId: "cli-main", sinkType: "cli", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => {} });
  const remaining = instance.getPendingPreCutoverPlayerPublications({ ...identity, limit: 32 }); assert.equal(remaining.length, 1); assert.notEqual(remaining[0].publicationId, first[0].publicationId);
  await assert.rejects(consumeLiveActionDisplay({ game: instance, action: { livePlayerDisplayEntries: [{ kind: "player_publication_delivery", ...remaining[0] }] }, consumerId: "cli-main", sinkType: "cli", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => { throw new Error("write failed"); } }), /write failed/);
  assert.equal(instance.completePlayerPublicationConsumerModeTransition(identity).reasonCode, "pre_cutover_delivery_pending"); assert.equal(instance.getPendingPreCutoverPlayerPublications({ ...identity, limit: 32 }).length, 1);
  await consumeLiveActionDisplay({ game: instance, action: { livePlayerDisplayEntries: [{ kind: "player_publication_delivery", ...remaining[0] }] }, consumerId: "cli-main", sinkType: "cli", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => {} });
  const completed = instance.completePlayerPublicationConsumerModeTransition(identity), replay = instance.completePlayerPublicationConsumerModeTransition(identity); assert.equal(completed, replay); assert.equal(replay.consumerGeneration, 1); assert.equal(instance.getPlayerPublicationDeliveryCandidates().includes(first[0].publicationId), false);
});

test("browser DOM evidence requires attachment and cleans up a failed sink completion", async () => {
  const missing = fakeDom(); assert.throws(() => appendBrowserPublicationNode({ document: missing.document, container: null, entry: { day: 1, phase: "day", message: "safe" } }), (error) => error.code === "browser_sink_container_missing");
  const throwing = fakeDom({ appendThrows: true }); assert.throws(() => appendBrowserPublicationNode({ document: throwing.document, container: throwing.container, entry: { day: 1, phase: "day", message: "safe" } }), /append failed/);
  const detached = fakeDom({ attach: false }); assert.throws(() => appendBrowserPublicationNode({ document: detached.document, container: detached.container, entry: { day: 1, phase: "day", message: "safe" } }), (error) => error.code === "browser_sink_attachment_failed"); assert.equal(detached.container.children.length, 0);

  const instance = game({ playerStructuredConsumerEnabled: false }), result = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), playerOnly = { ...result, livePlayerDisplayEntries: result.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery") }, dom = fakeDom(), bookkeeping = new Map(), originalComplete = instance.completePlayerPublicationSink.bind(instance); let firstComplete = true;
  instance.completePlayerPublicationSink = (capability) => { if (firstComplete) { firstComplete = false; throw new Error("completion failed"); } return originalComplete(capability); };
  const writeLegacy = async (entry, attempt) => { const node = appendBrowserPublicationNode({ document: dom.document, container: dom.container, entry }); node.dataset.publicationId = attempt.publicationId; return node; };
  await assert.rejects(consumeLiveActionDisplay({ game: instance, action: playerOnly, consumerId: "browser-main", sinkType: "browser", bookkeeping, writeStructured: async () => {}, writeLegacy }), /completion failed/); assert.equal(dom.container.children.length, 0); assert.equal(bookkeeping.size, 0); assert.equal(instance.playerPublicationDeliveryController.stateFor(result.deliveryPublicationIds[0]), "failed_retryable");
  await consumeLiveActionDisplay({ game: instance, action: playerOnly, consumerId: "browser-main", sinkType: "browser", bookkeeping, writeStructured: async () => {}, writeLegacy }); assert.equal(dom.container.children.length, 1); assert.equal(instance.playerPublicationDeliveryController.stateFor(result.deliveryPublicationIds[0]), "evidence_recorded");
  const node = dom.container.children[0], reconciled = reconcileBrowserPublicationNodes({ document: dom.document, container: dom.container, entries: [{ publicationId: result.deliveryPublicationIds[0], day: 1, phase: "player_question", message: "<img onerror=1>" }] }); assert.equal(reconciled[0], node); assert.equal(node.children[1].textContent, "<img onerror=1>");
});

test("CLI evidence waits for fulfilled output and evidence-only retry never writes twice", async () => {
  const instance = game({ playerStructuredConsumerEnabled: false }), result = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 0 }), playerOnly = { ...result, livePlayerDisplayEntries: result.livePlayerDisplayEntries.filter((entry) => entry.kind === "player_publication_delivery") }, publicationId = result.deliveryPublicationIds[0], failedBookkeeping = new Map();
  await assert.rejects(consumeLiveActionDisplay({ game: instance, action: playerOnly, consumerId: "cli-main", sinkType: "cli", bookkeeping: failedBookkeeping, writeStructured: async () => {}, writeLegacy: async () => Promise.reject(new Error("stdout failed")) }), /stdout failed/); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "failed_retryable"); assert.equal(instance.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds().has(publicationId), false);
  const bookkeeping = new Map(), output = [], originalRecord = instance.recordPreCutoverPlayerPublicationEvidence.bind(instance); let recordingFails = true; instance.recordPreCutoverPlayerPublicationEvidence = (receipt) => { if (recordingFails) { recordingFails = false; const error = new Error("evidence store failed"); throw error; } return originalRecord(receipt); };
  await consumeLiveActionDisplay({ game: instance, action: playerOnly, consumerId: "cli-main", sinkType: "cli", bookkeeping, writeStructured: async () => {}, writeLegacy: async (entry) => writeCliPublication({ entry, write: async (text) => output.push(text) }) }); assert.equal(output.length, 1); assert.equal(instance.playerPublicationDeliveryController.stateFor(publicationId), "evidence_recorded");
  const identity = [...bookkeeping.values()][0].identity; assert.equal(retryPreCutoverPlayerPublicationEvidence({ game: instance, deliveryIdentity: identity }).status, "evidence_recorded"); assert.equal(output.length, 1); assert.equal(output[0].includes("\u001b"), false);
});

test("cancel retains partial evidence and reset rejects every late transition capability", async () => {
  const events = [], instance = game({ playerStructuredConsumerEnabled: false, playerStructuredConsumerObserver: (event) => events.push(event) });
  await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }); instance.state.phase = "day_discussion"; await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" });
  const firstTransition = instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "structured" }), firstIdentity = transitionIdentity(firstTransition), firstCandidate = instance.getPendingPreCutoverPlayerPublications({ ...firstIdentity, limit: 1 })[0];
  await consumeLiveActionDisplay({ game: instance, action: { livePlayerDisplayEntries: [{ kind: "player_publication_delivery", ...firstCandidate }] }, consumerId: "browser-main", sinkType: "browser", bookkeeping: new Map(), writeStructured: async () => {}, writeLegacy: async () => {} });
  const cancelled = instance.cancelPlayerPublicationConsumerModeTransition(firstIdentity); assert.equal(cancelled.status, "cancelled"); assert.equal(instance.cancelPlayerPublicationConsumerModeTransition(firstIdentity), cancelled); assert.equal(instance.playerPublicationDeliveryController.preCutoverLegacyDeliveredPublicationIds().has(firstCandidate.publicationId), true);
  const nextTransition = instance.requestPlayerPublicationConsumerMode({ consumerId: "browser-main", sinkType: "browser", requestedMode: "structured" }), nextIdentity = transitionIdentity(nextTransition), remaining = instance.getPendingPreCutoverPlayerPublications({ ...nextIdentity, limit: 1 })[0]; assert.notEqual(nextTransition.modeTransitionId, firstTransition.modeTransitionId); assert.equal(nextTransition.pendingCount, 1);
  const attempt = instance.preparePlayerPublicationDelivery({ publicationId: remaining.publicationId, consumerId: "browser-main", sinkType: "browser", deliveryMode: "legacy_pre_cutover", modeTransitionId: nextTransition.modeTransitionId }), capability = instance.beginPlayerPublicationSink({ deliveryAttemptId: attempt.deliveryAttemptId }), receipt = instance.completePlayerPublicationSink(capability); instance.destroy();
  for (const operation of [() => instance.getPendingPreCutoverPlayerPublications({ ...nextIdentity, limit: 1 }), () => instance.completePlayerPublicationConsumerModeTransition(nextIdentity), () => instance.cancelPlayerPublicationConsumerModeTransition(nextIdentity), () => instance.recordPreCutoverPlayerPublicationEvidence(receipt)]) assert.throws(operation, (error) => error.code === "stale_publication_session");
  assert.equal(events.filter((event) => event.outcomeCategory === "consumer_mode_transition_cancelled").length, 1); assert.equal(events.filter((event) => event.outcomeCategory === "consumer_mode_transition_stale").length, 1); assert.equal(events.every((event) => !Object.hasOwn(event, "message") && !Object.hasOwn(event, "entry")), true);
});

function consumerIds() { let value = 0; return () => String(++value); }
function interpreterFor(acts) { return { async interpretPlayerInput(request) { return { schemaVersion: 1, requestId: request.requestId, correlationId: request.correlationId, serverCorrelationId: "server-1", result: { schemaVersion: 1, requestId: request.requestId, correlationId: request.correlationId, modelOutput: { schemaVersion: 1, alternatives: [{ alternativeId: "alternative-1", confidence: 1, speechActs: acts }] }, diagnostics: { providerName: "test", model: "test", attemptCount: 1, elapsedMs: 0 } } }; } }; }
function consumerGame(acts, consumer = true) { return WerewolfGame.create({ seed: 1, scenario: "sample", shuffleRoles: false, createId: consumerIds(), interpreterValidationEnabled: true, playerConversationCommitEnabled: true, playerStructuredConsumerEnabled: consumer, interpreterProvider: interpreterFor(acts), responseProvider: { async generateResponse() { return { text: "NPC response", providerName: "test", model: "test", usage: null, notes: [] }; } } }); }
function participants(instance) { return Object.fromEntries([["player", { participantId: "player", displayName: "Player" }], ...instance.state.players.map((player) => [player.id, { participantId: player.id, displayName: player.name }])]); }
async function committed(acts, raw = "hello") { const instance = consumerGame(acts, false); await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: raw }); return instance; }
function renderPublication(instance, publicationId = instance.state.conversation.publications[0].publicationId) { return renderPlayerPublication({ gameSessionId: instance.state.gameSessionId, conversation: instance.state.conversation, legacyPlayerLog: instance.state.playerLog, publicationId, publicParticipantsById: participants(instance), resolveCompatibilityMapping: (id) => instance.getPlayerLegacyDisplayCompatibilityRecord({ publicationId: id }) }); }

test("Phase 5 policy is default-off and strictly requires the Phase 4 writer", () => {
  assert.deepEqual(resolvePlayerStructuredConsumerPolicy({}), { enabled: false, playerConversationCommitRequired: true }); assert.throws(() => resolvePlayerStructuredConsumerPolicy({ playerStructuredConsumerMode: true }), (error) => error.code === "consumer_configuration_invalid"); assert.throws(() => parseConfig({ PLAYER_STRUCTURED_CONSUMER_MODE: "true" }), /requires PLAYER_CONVERSATION_COMMIT_MODE/); const enabled = parseConfig({ INTERPRETER_VALIDATION_MODE: "true", PLAYER_CONVERSATION_COMMIT_MODE: "true", PLAYER_STRUCTURED_CONSUMER_MODE: "true" }); assert.equal(enabled.playerStructuredConsumerMode, true); assert.equal(getRuntimeConfig(enabled).playerStructuredConsumerMode, true);
});

test("publication resolution renders immutable Unicode raw spans without authoritative mutation", async () => {
  const raw = "譌･・e\u0301 <script>x</script>", instance = await committed([{ type: "non_game_statement", sourceSpan: { start: 0, end: [...raw].length } }], raw), before = JSON.stringify(instance.state), result = renderPublication(instance); assert.equal(result.renderedText, raw); assert.equal(result.locale, "ja-JP"); assert.equal(JSON.stringify(instance.state), before); assert.equal(sanitizeTerminalText("a\u001bb"), "a[control]b");
});

test("canonical claim, suspicion, and vote segments use deterministic engine renderers", async () => {
  const claimGame = await committed([{ type: "result_claim", targetId: "npc1", result: "werewolf", sourceSpan: { start: 0, end: 5 } }]), first = renderPublication(claimGame), second = renderPublication(claimGame); assert.equal(first.renderedText, second.renderedText); assert.equal(first.renderedText.includes("Aoi"), true); assert.equal(/truth|true|false/i.test(first.renderedText), false);
  const suspicionGame = await committed([{ type: "suspicion", targetId: "npc2", sourceSpan: { start: 0, end: 5 } }]); assert.equal(renderPublication(suspicionGame).renderedText.includes("Beni"), true);
  const voteGame = consumerGame([], false); voteGame.state.phase = "vote"; const createId = consumerIds(), binding = createPhase3Binding({ state: voteGame.state, rawText: "vote!", targetNpcId: "npc1", createId }), prepared = preparePlayerConversationCommit({ state: voteGame.state, binding, alternative: { alternativeId: "vote-alt", confidence: 1, speechActs: [{ type: "vote_declaration", targetId: "npc2", sourceSpan: { start: 0, end: 5 } }] }, targetNpcId: "npc1", createId }); for (const [key, values] of Object.entries(prepared.delta.objects)) voteGame.state.conversation[key].push(...structuredClone(values)); voteGame.state.playerLog.push(structuredClone(prepared.delta.legacyDelta.playerLogEntry)); assert.equal(renderPublication(voteGame).renderedText.includes("Beni"), true);
});

test("dangling, duplicate, and invalid publication graphs fail closed with typed consumer errors", async () => {
  const instance = await committed([{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }]), publicationId = instance.state.conversation.publications[0].publicationId, common = { gameSessionId: instance.state.gameSessionId, legacyPlayerLog: instance.state.playerLog, publicationId, publicParticipantsById: participants(instance) }; const missingInput = structuredClone(instance.state.conversation); missingInput.inputRecords = []; assert.throws(() => renderPlayerPublication({ ...common, conversation: missingInput }), (error) => error.code === "dangling_input_reference"); const duplicate = structuredClone(instance.state.conversation); duplicate.publications.push(structuredClone(duplicate.publications[0])); assert.throws(() => renderPlayerPublication({ ...common, conversation: duplicate }), (error) => error.code === "duplicate_publication"); const missingParticipant = participants(instance); delete missingParticipant.npc1; const claimInstance = await committed([{ type: "result_claim", targetId: "npc1", result: "werewolf", sourceSpan: { start: 0, end: 5 } }]); assert.throws(() => renderPlayerPublication({ gameSessionId: claimInstance.state.gameSessionId, conversation: claimInstance.state.conversation, legacyPlayerLog: claimInstance.state.playerLog, publicationId: claimInstance.state.conversation.publications[0].publicationId, publicParticipantsById: missingParticipant }), (error) => error.code === "missing_public_participant_projection"); assert.throws(() => renderPlayerPublication({ ...common, activeGameSessionId: "game-new", conversation: instance.state.conversation }), (error) => error.code === "mismatched_session");
});

test("Phase 5 cutover emits one structured entry, suppresses legacy display, and preserves NPC order", async () => {
  const observed = [], visible = [], instance = consumerGame([{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }], true); instance.playerPublicationDeliveryController.observer = (entry) => observed.push(entry); const result = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }); assert.equal(result.structuredPlayerEntries.length, 1); assert.equal(result.playerFacingEntries.length, 2); await deliverLivePlayerEntries({ game: instance, entries: result.livePlayerDisplayEntries, consumerId: "test", sinkType: "browser", writeStructured: async (entry) => visible.push(entry), writeLegacy: async (entry) => visible.push(entry) }); assert.equal(visible[0].structured, true); assert.equal(visible[0].message, "hello"); assert.equal(visible[1].message, "Aoi: NPC response"); assert.equal(observed.filter((entry) => entry.outcomeCategory === "publication_acknowledged").length, 1);
});

test("exact replay emits no display/history entry and never rewinds the consumer cursor", async () => {
  const instance = consumerGame([{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }], true), first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }); await deliverLivePlayerEntries({ game: instance, entries: first.livePlayerDisplayEntries, consumerId: "test", sinkType: "cli", writeStructured: async () => {}, writeLegacy: async () => {} }); const record = instance.state.conversation.idempotencyRecords[0], version = instance.state.stateVersion, replay = await instance.dispatchPlayerAction({ type: "ask_npc", replayRequestId: record.requestId, replayRequestFingerprint: record.requestFingerprint }); assert.deepEqual(replay.structuredPlayerEntries, []); assert.deepEqual(replay.livePlayerDisplayEntries, []); assert.equal(instance.state.stateVersion, version);
});

test("OFF-to-ON does not backfill old publications and OFF rollback does not delete records", async () => {
  const instance = consumerGame([{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }], false), legacy = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }); assert.equal(legacy.structuredPlayerEntries.length, 0); await deliverLivePlayerEntries({ game: instance, entries: legacy.livePlayerDisplayEntries, consumerId: "test", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} }); instance.state.phase = "day_discussion"; instance.requestPlayerPublicationConsumerMode({ consumerId: "test", sinkType: "browser", requestedMode: "structured" }); const next = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello" }); assert.equal(next.structuredPlayerEntries.length, 1); assert.equal(instance.state.conversation.publications.length, 2); instance.requestPlayerPublicationConsumerMode({ consumerId: "test", sinkType: "browser", requestedMode: "legacy" }); await instance.dispatchPlayerAction({ type: "get_state" }); assert.equal(instance.state.conversation.publications.length, 2);
});

test("slot ordering is authoritative while append order and legacy array position are ignored", async () => {
  const first = await committed([{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }]), publicationId = first.state.conversation.publications[0].publicationId, entries = renderUnacknowledgedPlayerPublications({ gameSessionId: first.state.gameSessionId, conversation: first.state.conversation, legacyPlayerLog: first.state.playerLog, publicParticipantsById: participants(first), publicationIds: [publicationId], resolveCompatibilityMapping: (id) => first.getPlayerLegacyDisplayCompatibilityRecord({ publicationId: id }) }); assert.equal(entries.length, 1); const projected = projectMappedPlayerEntries({ legacyEntries: first.state.playerLog, legacyLogStartOrder: 0, structuredEntries: entries }); assert.equal(projected[entries[0].legacyLogAppendOrder].message, "hello"); assert.equal(projected.filter((entry) => entry.structured).length, 1);
});

test("same-message multiple turns, stale cursors, partial acknowledgement, and NPC entries retain exact identity", async () => {
  const instance = consumerGame([{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }], true), first = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: 1 }); await deliverLivePlayerEntries({ game: instance, entries: first.livePlayerDisplayEntries, consumerId: "test", sinkType: "browser", writeStructured: async () => {}, writeLegacy: async () => {} }); const firstPublication = first.structuredPlayerEntries[0].publicationId; instance.state.phase = "day_discussion"; instance.interpreterProvider = interpreterFor([{ type: "non_game_statement", sourceSpan: { start: 0, end: 5 } }]); const second = await instance.dispatchPlayerAction({ type: "ask_npc", targetId: "npc1", input: "hello", logCursor: first.nextLogCursor }), secondPublication = second.structuredPlayerEntries.find((entry) => entry.publicationId !== firstPublication); assert.ok(secondPublication); assert.equal(second.playerFacingEntries.filter((entry) => entry.structured).length, 1); assert.equal(second.playerFacingEntries.some((entry) => entry.message === "Aoi: NPC response"), true); assert.notEqual(instance.getPlayerLegacyDisplayCompatibilityRecord({ publicationId: firstPublication }).legacyLogAppendOrder, instance.getPlayerLegacyDisplayCompatibilityRecord({ publicationId: secondPublication.publicationId }).legacyLogAppendOrder);
});

test("browser and CLI adapters select derived entries and retain safe output boundaries", () => {
  const browser = readFileSync(new URL("../public/browserApp.mjs", import.meta.url), "utf8"), cli = readFileSync(new URL("../src/cli.mjs", import.meta.url), "utf8"); assert.match(browser, /result\.livePlayerDisplayEntries\.length/); assert.equal(browser.includes("playerFacingLog.push(...structuredClone(result.playerFacingEntries))"), false); assert.match(browser, /appendBrowserPublicationNode/); assert.equal(browser.includes("message.innerHTML = entry.message"), false); assert.match(cli, /action\?\.livePlayerDisplayEntries/); assert.match(cli, /sanitizeTerminalText/);
});
